// Copy for: Funding (loans), WhatsApp bot, GST helper, weekly report, security/team/activity, agentic plans, recovered counter.

export const enV3 = {
  "voice.processing": "DHAN is understanding…",
  "voice.failed": "Couldn't catch that. Try again or type below.",

  "nav.loans": "Funding",
  "nav.bot": "WhatsApp bot",
  "nav.gst": "GST helper",
  "nav.reports": "Weekly report",
  "nav.g.money": "Money",
  "nav.g.intel": "Intelligence",
  "nav.g.grow": "Grow",
  "nav.g.tools": "Tools",
  "ev.due_changed": "Due date moved from {old} to {new}",

  // funding
  "ln.title": "Funding",
  "ln.sub": "Loan offers matched to your verified numbers. Apply in a tap: lenders see your Credit Passport, never your raw transactions.",
  "ln.simBanner": "Demo: the lenders are fictional and no money moves. Offers, rates and approvals are simulated from your real numbers.",
  "ln.eligibleLabel": "You're eligible for up to",
  "ln.profile": "Your numbers",
  "ln.score": "Credit readiness",
  "ln.months": "Months of records",
  "ln.income": "Avg monthly income",
  "ln.recv": "Open invoices (≤60 days late)",
  "ln.offers": "Offers for you",
  "ln.noOffers": "No offers yet",
  "ln.noOffersBody": "Keep recording for a few more weeks and improve your score. The lenders below show exactly what each one needs.",
  "ln.upTo": "Up to {amount}",
  "ln.rate": "{rate}% p.a.",
  "ln.fee": "{pct}% fee",
  "ln.speed": "Decision in {speed}",
  "ln.tenure": "Tenure",
  "ln.tenureMonths": "{n} months",
  "ln.emi": "EMI ≈ {amount}/month",
  "ln.apply": "Apply",
  "ln.applyTitle": "Apply to {lender}",
  "ln.amount": "Loan amount",
  "ln.total": "Total repayment ≈ {amount}",
  "ln.feeAmount": "Processing fee {amount}",
  "ln.consent": "Applying shares a read-only Credit Passport (score, 90-day totals, forecast status) with {lender} for 30 days. You can revoke it any time from the Credit page.",
  "ln.submit": "Submit application",
  "ln.submitting": "Submitting…",
  "ln.submitted": "Application sent to {lender}",
  "ln.fail": "Couldn't submit. Please try again.",
  "ln.notEligible": "Not eligible yet",
  "ln.need.score": "Credit readiness {need}+ (you: {have})",
  "ln.need.months": "{need}+ months of records (you: {have})",
  "ln.need.income": "Average monthly income {need}+ (you: {have})",
  "ln.need.receivables": "Open invoices worth {need}+ (you: {have})",
  "ln.improve": "See how to improve",
  "ln.apps": "Your applications",
  "ln.stage.submitted": "Submitted",
  "ln.stage.reviewing": "Under review",
  "ln.stage.approved": "Offer ready",
  "ln.stage.accepted": "Accepted",
  "ln.stage.declined": "Declined",
  "ln.stage.withdrawn": "Withdrawn",
  "ln.accept": "Accept offer",
  "ln.accepted": "Accepted. With a real lender, funds would now be disbursed.",
  "ln.withdraw": "Withdraw",
  "ln.openDesk": "Open the lender's desk (demo)",
  "ln.terms": "{amount} at {rate}% for {n} months",
  "ln.declinedReason": "Reason: {reason}",
  "ln.waiting": "Waiting for the lender…",
  "ln.type.NBFC": "NBFC",
  "ln.type.Bank": "Bank",
  "ln.type.Fintech": "Fintech",
  "ln.type.Invoice financing": "Invoice financing",
  "notif.loan_approved": "{lender} approved {amount} at {rate}%",
  "notif.loan_approvedBody": "Open Funding to review and accept",
  "notif.loan_declined": "{lender} declined your application",
  "notif.loan_viewed": "{lender} opened your application",
  "ld.title": "Lender desk",
  "ld.sub": "What {lender} sees when a borrower applies",
  "ld.demoBanner": "Demo screen: act as the lender and watch the borrower's alert arrive live in the other window.",
  "ld.application": "Loan application",
  "ld.requested": "Requested",
  "ld.decision": "Your decision",
  "ld.approve": "Approve as requested",
  "ld.counter": "Counter-offer",
  "ld.decline": "Decline",
  "ld.counterAmount": "Amount (₹)",
  "ld.counterRate": "Rate % p.a.",
  "ld.reason": "Reason (optional)",
  "ld.send": "Send decision",
  "ld.sent": "Decision sent. The borrower has been notified.",
  "ld.status": "Status",

  // whatsapp bot
  "bt.title": "WhatsApp bot",
  "bt.sub": "Log entries by message, voice note or bill photo, and ask about your business. This is the chat a shopkeeper would use.",
  "bt.demoNote": "Simulated chat. With WhatsApp keys in .env, the same bot answers on a real number.",
  "bt.placeholder": "Type a message…",
  "bt.send": "Send",
  "bt.photo": "Send a bill photo",
  "bt.record": "Record a voice note",
  "bt.recording": "Recording… tap to send",
  "bt.c1": "paid 500 to Sharma Transport for petrol",
  "bt.c2": "Who owes me money?",
  "bt.c3": "What's my GST this month?",
  "bt.c4": "UNDO",
  "bt.c5": "HELP",
  "bt.save": "Save",
  "bt.discard": "Discard",
  "bt.saved": "Saved",
  "bt.discarded": "Discarded",
  "bt.undone": "Removed",
  "bt.clear": "Clear chat",
  "bt.name": "DHAN",
  "bt.online": "online",
  "bt.fail": "Couldn't send that. Please try again.",
  "bt.logged": "Logged",
  "bt.billDraft": "Bill draft",
  "bt.voiceNote": "Voice note",
  "bt.photoSent": "Photo",
  "bt.noMic": "Microphone isn't available here.",

  // gst
  "gs.title": "GST helper",
  "gs.sub": "Estimated GST payable, input credit and filing dates, from your own books.",
  "gs.banner": "Estimates for planning, based on the assumptions below. Not a filing. Confirm with your CA.",
  "gs.insufficient": "Add some sales and purchase entries and your GST estimate will appear here.",
  "gs.period": "Return period {period}",
  "gs.net": "Estimated GST payable",
  "gs.output": "GST on sales",
  "gs.itc": "Input tax credit",
  "gs.paid": "Paid so far",
  "gs.gstr3b": "GSTR-3B due {date}",
  "gs.gstr1": "GSTR-1 due {date}",
  "gs.daysLeft": "{n} days left",
  "gs.pastDue": "Past the due date",
  "gs.trend": "Output tax vs input credit",
  "gs.legendOut": "GST on sales",
  "gs.legendIn": "Input credit",
  "gs.month": "Month",
  "gs.sales": "Sales",
  "gs.netCol": "Net payable",
  "gs.left": "Input credit you're leaving on the table",
  "gs.leftBody": "These bills have no supplier GSTIN, so the credit can't be claimed. Ask each supplier for a GST invoice.",
  "gs.potential": "worth about {amount} of credit",
  "gs.bills": "{n} bills",
  "gs.noMissing": "Every eligible bill has a GSTIN. Nothing is left on the table.",
  "gs.assumptions": "Assumptions",
  "gs.rate": "GST rate on your sales",
  "gs.inclusive": "Sale amounts include GST",
  "gs.exclusive": "GST is added on top",
  "gs.note": "Fuel, food, wages and tax payments never carry input credit. Foreign-billed services (cloud, ads) fall under reverse charge, so ask your CA.",
  "gs.export": "Download CA pack (CSV)",
  "gs.askAi": "Ask DHAN AI about GST",
  "gs.reg": "Purchase register",

  // weekly report
  "rp.title": "Weekly report",
  "rp.sub": "Your week on one page, written by DHAN AI.",
  "rp.print": "Print or save as PDF",
  "rp.email": "Email this report",
  "rp.emailTo": "Send to",
  "rp.send": "Send",
  "rp.sending": "Sending…",
  "rp.sent": "Report sent to {to}",
  "rp.simulated": "Simulated: connect SMTP in .env to deliver real email.",
  "rp.fail": "Couldn't send the report.",
  "rp.week": "{from} to {to}",
  "rp.noteFrom": "A note from DHAN AI",
  "rp.groq": "Written by Groq",
  "rp.rules": "Auto-written",
  "rp.numbers": "The numbers",
  "rp.income": "Income",
  "rp.expenses": "Expenses",
  "rp.net": "Net",
  "rp.cash": "Cash in hand",
  "rp.spend": "Where the money went",
  "rp.vendors": "Biggest vendors",
  "rp.owed": "Money owed to you",
  "rp.overdue": "{amount} overdue",
  "rp.outlook": "Cash outlook",
  "rp.safe": "Cash looks safe for the next 45 days.",
  "rp.tight": "Cash gets tight around {date}.",
  "rp.focus": "Focus for next week",
  "rp.recovered": "Recovered after DHAN reminders",
  "rp.gst": "GST",
  "rp.insights": "What stood out",
  "rp.footer": "Generated by DHAN AI from your own records. Estimates are indicative.",
  "set.weekly": "Weekly report by email",
  "set.weeklyBody": "Every Monday morning DHAN AI emails you last week's report.",
  "set.weeklyEmail": "Email address",
  "set.weeklyOn": "Email me every Monday",
  "set.weeklySave": "Save",
  "set.weeklySaved": "Report settings saved",
  "set.weeklyNeedEmail": "Add an email address first.",

  // security, team, activity
  "set.security": "Security",
  "set.twoFactor": "Two-step login",
  "set.twoFactorBody": "After your password, DHAN asks for a 6-digit code sent to your phone.",
  "set.twoFactorSaved": "Security settings saved",
  "set.team": "Team",
  "set.teamBody": "Give your accountant read-only access. They see everything and can change nothing.",
  "set.invite": "Add an accountant",
  "set.inviteName": "Name",
  "set.invitePhone": "Phone number",
  "set.invitePassword": "Temporary password",
  "set.inviteAdd": "Add accountant",
  "set.roleOwner": "Owner",
  "set.roleAccountant": "Accountant · read-only",
  "set.remove": "Remove",
  "set.teamAdded": "Accountant added",
  "set.teamFail": "Couldn't add that person. Is the phone number already registered?",
  "set.activity": "Activity log",
  "set.activityBody": "Who did what, and when.",
  "set.activityEmpty": "Nothing has happened yet.",
  "aud.auth.login": "Signed in",
  "aud.auth.otp_login": "Signed in with a code",
  "aud.transaction.create": "Added a transaction: {vendor}",
  "aud.transaction.delete": "Deleted a transaction: {vendor}",
  "aud.transaction.import": "Imported {imported} transactions",
  "aud.udhaar.create": "Added udhaar for {party}",
  "aud.udhaar.send": "Sent a payment link to {party}",
  "aud.udhaar.payment": "Recorded a payment from {party}",
  "aud.udhaar.settle": "Settled {party}",
  "aud.udhaar.claim_confirmed": "Confirmed a payment from {party}",
  "aud.udhaar.claim_rejected": "Rejected a payment claim from {party}",
  "aud.udhaar.delete": "Deleted the udhaar entry for {party}",
  "aud.passport.create": "Created a Credit Passport for {label}",
  "aud.passport.revoke": "Revoked a Credit Passport",
  "aud.settings.upi": "Changed the UPI ID",
  "aud.settings.weekly_report": "Changed weekly report settings",
  "aud.security.two_factor": "Changed two-step login",
  "aud.team.add": "Added {name} to the team",
  "aud.team.remove": "Removed {name} from the team",
  "aud.ai.action": "DHAN AI action: {type}",
  "aud.loan.apply": "Applied to {lender}",
  "aud.loan.accept": "Accepted an offer from {lender}",
  "aud.loan.withdraw": "Withdrew the application to {lender}",
  "aud.bot.transaction": "Bot logged: {vendor}",
  "aud.bot.undo": "Bot undid: {vendor}",
  "aud.report.email": "Emailed the weekly report",
  "aud.unknown": "Activity",
  "ro.banner": "Read-only access: you can see everything but cannot change it.",
  "ro.badge": "Read-only",
  "auth.otpTitle": "Enter your code",
  "auth.otpSub": "We sent a 6-digit code to {phone}.",
  "auth.code": "6-digit code",
  "auth.verify": "Verify and sign in",
  "auth.useCode": "Sign in with a code instead",
  "auth.usePassword": "Use my password instead",
  "auth.sendCode": "Send me a code",
  "auth.demoNote": "Demo mode: your code shows here instead of arriving by WhatsApp or SMS.",
  "auth.demoCode": "Your DHAN login code is {code}",
  "auth.codeWrong": "That code is wrong or has expired.",
  "auth.resend": "Send a new code",
  "auth.locked": "Too many attempts. Please wait a few minutes.",

  // agentic plans
  "act.title": "Proposed plan",
  "act.noteNothing": "Nothing needs fixing right now.",
  "act.before": "Lowest cash point today",
  "act.after": "With this plan",
  "act.resolves": "Keeps you above your safety buffer",
  "act.stillTight": "Still below your safety buffer. Consider more steps.",
  "act.assume": "Assumes customers you chase pay within 4 days, weighted by how reliably each pays.",
  "act.approve": "Approve",
  "act.skip": "Skip",
  "act.approveAll": "Approve all",
  "act.done": "Done",
  "act.skipped": "Skipped",
  "act.failed": "Failed",
  "act.send_reminders": "Remind {n} customers who owe {amount}",
  "act.delay_bill": "Pay {party} on {to} instead of {from}",
  "act.delay_billDetail": "Moves {amount} later",
  "act.enable_auto_remind": "Turn on auto-reminders for {n} invoices",
  "act.result.send_reminders": "Reminders sent to {sent} of {total}",
  "act.result.delay_bill": "Due date moved to {date}",
  "act.result.enable_auto_remind": "Auto-reminders are on for {n}",
  "act.fail": "Couldn't do that. Please try again.",

  // recovered
  "rv.title": "Recovered by DHAN",
  "rv.body": "{amount} received on {n} invoices after DHAN reminded the customer",
};

export const hiV3 = {
  "voice.processing": "DHAN समझ रहा है…",
  "voice.failed": "आवाज़ समझ नहीं आई। फिर कोशिश करें या नीचे लिखें।",

  "nav.loans": "फंडिंग",
  "nav.bot": "WhatsApp बॉट",
  "nav.gst": "GST सहायक",
  "nav.reports": "साप्ताहिक रिपोर्ट",
  "nav.g.money": "पैसा",
  "nav.g.intel": "बुद्धिमत्ता",
  "nav.g.grow": "बढ़ोतरी",
  "nav.g.tools": "औज़ार",
  "ev.due_changed": "देय तारीख {old} से बदलकर {new} हुई",

  "ln.title": "फंडिंग",
  "ln.sub": "आपके सत्यापित आंकड़ों से मेल खाते लोन ऑफ़र। एक टैप में आवेदन करें: ऋणदाता आपका क्रेडिट पासपोर्ट देखते हैं, कच्चे लेन-देन नहीं।",
  "ln.simBanner": "डेमो: ऋणदाता काल्पनिक हैं और कोई पैसा नहीं हिलता। ऑफ़र, ब्याज दरें और मंज़ूरी आपके असली आंकड़ों से सिमुलेट होती हैं।",
  "ln.eligibleLabel": "आप इतने तक के लिए पात्र हैं",
  "ln.profile": "आपके आंकड़े",
  "ln.score": "क्रेडिट तैयारी",
  "ln.months": "रिकॉर्ड के महीने",
  "ln.income": "औसत मासिक आमदनी",
  "ln.recv": "खुले इनवॉइस (≤60 दिन देर)",
  "ln.offers": "आपके लिए ऑफ़र",
  "ln.noOffers": "अभी कोई ऑफ़र नहीं",
  "ln.noOffersBody": "कुछ और हफ़्ते रिकॉर्ड रखें और स्कोर सुधारें। नीचे हर ऋणदाता की ज़रूरत साफ़ दिखती है।",
  "ln.upTo": "{amount} तक",
  "ln.rate": "{rate}% वार्षिक",
  "ln.fee": "{pct}% शुल्क",
  "ln.speed": "फ़ैसला {speed} में",
  "ln.tenure": "अवधि",
  "ln.tenureMonths": "{n} महीने",
  "ln.emi": "EMI ≈ {amount}/माह",
  "ln.apply": "आवेदन करें",
  "ln.applyTitle": "{lender} में आवेदन",
  "ln.amount": "लोन राशि",
  "ln.total": "कुल चुकौती ≈ {amount}",
  "ln.feeAmount": "प्रोसेसिंग शुल्क {amount}",
  "ln.consent": "आवेदन करने पर {lender} के साथ 30 दिन के लिए एक रीड-ओनली क्रेडिट पासपोर्ट (स्कोर, 90 दिन के कुल आंकड़े, पूर्वानुमान की स्थिति) साझा होता है। आप इसे क्रेडिट पेज से कभी भी रद्द कर सकते हैं।",
  "ln.submit": "आवेदन भेजें",
  "ln.submitting": "भेजा जा रहा है…",
  "ln.submitted": "{lender} को आवेदन भेज दिया गया",
  "ln.fail": "भेज नहीं सके। फिर कोशिश करें।",
  "ln.notEligible": "अभी पात्र नहीं",
  "ln.need.score": "क्रेडिट तैयारी {need}+ (आपकी: {have})",
  "ln.need.months": "{need}+ महीने का रिकॉर्ड (आपका: {have})",
  "ln.need.income": "औसत मासिक आमदनी {need}+ (आपकी: {have})",
  "ln.need.receivables": "{need}+ के खुले इनवॉइस (आपके: {have})",
  "ln.improve": "सुधार का तरीका देखें",
  "ln.apps": "आपके आवेदन",
  "ln.stage.submitted": "भेजा गया",
  "ln.stage.reviewing": "समीक्षा में",
  "ln.stage.approved": "ऑफ़र तैयार",
  "ln.stage.accepted": "स्वीकृत",
  "ln.stage.declined": "अस्वीकृत",
  "ln.stage.withdrawn": "वापस लिया",
  "ln.accept": "ऑफ़र स्वीकारें",
  "ln.accepted": "स्वीकार किया। असली ऋणदाता के साथ अब रकम जारी होती।",
  "ln.withdraw": "वापस लें",
  "ln.openDesk": "ऋणदाता का डेस्क खोलें (डेमो)",
  "ln.terms": "{amount}, {rate}% पर, {n} महीने",
  "ln.declinedReason": "कारण: {reason}",
  "ln.waiting": "ऋणदाता का इंतज़ार…",
  "ln.type.NBFC": "NBFC",
  "ln.type.Bank": "बैंक",
  "ln.type.Fintech": "फ़िनटेक",
  "ln.type.Invoice financing": "इनवॉइस फ़ाइनेंसिंग",
  "notif.loan_approved": "{lender} ने {rate}% पर {amount} मंज़ूर किए",
  "notif.loan_approvedBody": "देखने और स्वीकारने के लिए फंडिंग खोलें",
  "notif.loan_declined": "{lender} ने आपका आवेदन अस्वीकार किया",
  "notif.loan_viewed": "{lender} ने आपका आवेदन खोला",
  "ld.title": "ऋणदाता डेस्क",
  "ld.sub": "आवेदन आने पर {lender} को क्या दिखता है",
  "ld.demoBanner": "डेमो स्क्रीन: ऋणदाता बनकर फ़ैसला दें और दूसरी विंडो में उधारकर्ता का अलर्ट लाइव आते देखें।",
  "ld.application": "लोन आवेदन",
  "ld.requested": "मांगा गया",
  "ld.decision": "आपका फ़ैसला",
  "ld.approve": "जैसा मांगा वैसा मंज़ूर",
  "ld.counter": "जवाबी ऑफ़र",
  "ld.decline": "अस्वीकार",
  "ld.counterAmount": "राशि (₹)",
  "ld.counterRate": "ब्याज % वार्षिक",
  "ld.reason": "कारण (वैकल्पिक)",
  "ld.send": "फ़ैसला भेजें",
  "ld.sent": "फ़ैसला भेज दिया। उधारकर्ता को सूचना मिल गई।",
  "ld.status": "स्थिति",

  "bt.title": "WhatsApp बॉट",
  "bt.sub": "संदेश, वॉइस नोट या बिल की फ़ोटो से एंट्री दर्ज करें और अपने व्यापार के बारे में पूछें। दुकानदार इसी चैट का इस्तेमाल करेगा।",
  "bt.demoNote": "सिमुलेटेड चैट। .env में WhatsApp कुंजियां डालने पर यही बॉट असली नंबर पर जवाब देगा।",
  "bt.placeholder": "संदेश लिखें…",
  "bt.send": "भेजें",
  "bt.photo": "बिल की फ़ोटो भेजें",
  "bt.record": "वॉइस नोट रिकॉर्ड करें",
  "bt.recording": "रिकॉर्ड हो रहा है… भेजने के लिए दबाएं",
  "bt.c1": "शर्मा ट्रांसपोर्ट को 500 रुपये दिए पेट्रोल के",
  "bt.c2": "मुझसे किसको कितना लेना है?",
  "bt.c3": "इस महीने मेरा GST कितना है?",
  "bt.c4": "UNDO",
  "bt.c5": "HELP",
  "bt.save": "सहेजें",
  "bt.discard": "हटाएं",
  "bt.saved": "सहेजा गया",
  "bt.discarded": "हटा दिया",
  "bt.undone": "हटाया गया",
  "bt.clear": "चैट साफ़ करें",
  "bt.name": "DHAN",
  "bt.online": "ऑनलाइन",
  "bt.fail": "भेज नहीं सके। फिर कोशिश करें।",
  "bt.logged": "दर्ज हुआ",
  "bt.billDraft": "बिल का मसौदा",
  "bt.voiceNote": "वॉइस नोट",
  "bt.photoSent": "फ़ोटो",
  "bt.noMic": "यहां माइक्रोफ़ोन उपलब्ध नहीं है।",

  "gs.title": "GST सहायक",
  "gs.sub": "आपके अपने खातों से अनुमानित GST देय, इनपुट क्रेडिट और फ़ाइलिंग की तारीखें।",
  "gs.banner": "योजना के लिए अनुमान, नीचे की मान्यताओं पर आधारित। यह फ़ाइलिंग नहीं है। अपने CA से पक्का करें।",
  "gs.insufficient": "कुछ बिक्री और खरीद की एंट्री जोड़ें, फिर आपका GST अनुमान यहां दिखेगा।",
  "gs.period": "रिटर्न अवधि {period}",
  "gs.net": "अनुमानित GST देय",
  "gs.output": "बिक्री पर GST",
  "gs.itc": "इनपुट टैक्स क्रेडिट",
  "gs.paid": "अब तक चुकाया",
  "gs.gstr3b": "GSTR-3B की तारीख {date}",
  "gs.gstr1": "GSTR-1 की तारीख {date}",
  "gs.daysLeft": "{n} दिन बाकी",
  "gs.pastDue": "अंतिम तारीख निकल चुकी",
  "gs.trend": "बिक्री पर टैक्स बनाम इनपुट क्रेडिट",
  "gs.legendOut": "बिक्री पर GST",
  "gs.legendIn": "इनपुट क्रेडिट",
  "gs.month": "महीना",
  "gs.sales": "बिक्री",
  "gs.netCol": "शुद्ध देय",
  "gs.left": "जो इनपुट क्रेडिट आप छोड़ रहे हैं",
  "gs.leftBody": "इन बिलों पर आपूर्तिकर्ता का GSTIN नहीं है, इसलिए क्रेडिट नहीं मिल सकता। हर आपूर्तिकर्ता से GST इनवॉइस मांगें।",
  "gs.potential": "लगभग {amount} का क्रेडिट",
  "gs.bills": "{n} बिल",
  "gs.noMissing": "हर योग्य बिल पर GSTIN है। कुछ भी छूट नहीं रहा।",
  "gs.assumptions": "मान्यताएं",
  "gs.rate": "आपकी बिक्री पर GST दर",
  "gs.inclusive": "बिक्री राशि में GST शामिल है",
  "gs.exclusive": "GST ऊपर से जुड़ता है",
  "gs.note": "ईंधन, खान-पान, वेतन और कर भुगतान पर इनपुट क्रेडिट नहीं मिलता। विदेश से बिल वाली सेवाएं (क्लाउड, विज्ञापन) रिवर्स चार्ज में आती हैं, अपने CA से पूछें।",
  "gs.export": "CA पैक डाउनलोड करें (CSV)",
  "gs.askAi": "GST के बारे में DHAN AI से पूछें",
  "gs.reg": "खरीद रजिस्टर",

  "rp.title": "साप्ताहिक रिपोर्ट",
  "rp.sub": "आपका हफ़्ता एक पन्ने पर, DHAN AI की कलम से।",
  "rp.print": "प्रिंट करें या PDF सहेजें",
  "rp.email": "यह रिपोर्ट ईमेल करें",
  "rp.emailTo": "किसको भेजें",
  "rp.send": "भेजें",
  "rp.sending": "भेजा जा रहा है…",
  "rp.sent": "रिपोर्ट {to} को भेजी गई",
  "rp.simulated": "सिमुलेटेड: असली ईमेल के लिए .env में SMTP जोड़ें।",
  "rp.fail": "रिपोर्ट नहीं भेज सके।",
  "rp.week": "{from} से {to}",
  "rp.noteFrom": "DHAN AI की ओर से एक नोट",
  "rp.groq": "Groq द्वारा लिखा",
  "rp.rules": "अपने-आप लिखा",
  "rp.numbers": "आंकड़े",
  "rp.income": "आमदनी",
  "rp.expenses": "खर्चे",
  "rp.net": "शुद्ध",
  "rp.cash": "हाथ में नकद",
  "rp.spend": "पैसा कहां गया",
  "rp.vendors": "सबसे बड़े विक्रेता",
  "rp.owed": "आपको मिलने वाला पैसा",
  "rp.overdue": "{amount} देर से",
  "rp.outlook": "कैश का अनुमान",
  "rp.safe": "अगले 45 दिन कैश सुरक्षित दिखता है।",
  "rp.tight": "{date} के आसपास कैश तंग होगा।",
  "rp.focus": "अगले हफ़्ते का ध्यान",
  "rp.recovered": "DHAN की याद के बाद वसूला",
  "rp.gst": "GST",
  "rp.insights": "जो बातें अलग दिखीं",
  "rp.footer": "DHAN AI द्वारा आपके अपने रिकॉर्ड से बनी। अनुमान सांकेतिक हैं।",
  "set.weekly": "ईमेल पर साप्ताहिक रिपोर्ट",
  "set.weeklyBody": "हर सोमवार सुबह DHAN AI आपको पिछले हफ़्ते की रिपोर्ट ईमेल करता है।",
  "set.weeklyEmail": "ईमेल पता",
  "set.weeklyOn": "हर सोमवार ईमेल करें",
  "set.weeklySave": "सहेजें",
  "set.weeklySaved": "रिपोर्ट सेटिंग्स सहेजी गईं",
  "set.weeklyNeedEmail": "पहले ईमेल पता जोड़ें।",

  "set.security": "सुरक्षा",
  "set.twoFactor": "दो-चरणीय लॉगिन",
  "set.twoFactorBody": "पासवर्ड के बाद DHAN आपके फ़ोन पर भेजा 6 अंकों का कोड मांगता है।",
  "set.twoFactorSaved": "सुरक्षा सेटिंग्स सहेजी गईं",
  "set.team": "टीम",
  "set.teamBody": "अपने अकाउंटेंट को रीड-ओनली एक्सेस दें। वे सब देख सकते हैं, पर कुछ बदल नहीं सकते।",
  "set.invite": "अकाउंटेंट जोड़ें",
  "set.inviteName": "नाम",
  "set.invitePhone": "फ़ोन नंबर",
  "set.invitePassword": "अस्थायी पासवर्ड",
  "set.inviteAdd": "अकाउंटेंट जोड़ें",
  "set.roleOwner": "मालिक",
  "set.roleAccountant": "अकाउंटेंट · रीड-ओनली",
  "set.remove": "हटाएं",
  "set.teamAdded": "अकाउंटेंट जुड़ गए",
  "set.teamFail": "इन्हें जोड़ नहीं सके। क्या यह फ़ोन नंबर पहले से पंजीकृत है?",
  "set.activity": "गतिविधि लॉग",
  "set.activityBody": "किसने क्या किया, और कब।",
  "set.activityEmpty": "अभी कुछ नहीं हुआ।",
  "aud.auth.login": "साइन इन किया",
  "aud.auth.otp_login": "कोड से साइन इन किया",
  "aud.transaction.create": "लेन-देन जोड़ा: {vendor}",
  "aud.transaction.delete": "लेन-देन हटाया: {vendor}",
  "aud.transaction.import": "{imported} लेन-देन इंपोर्ट किए",
  "aud.udhaar.create": "{party} के लिए उधार जोड़ा",
  "aud.udhaar.send": "{party} को भुगतान लिंक भेजा",
  "aud.udhaar.payment": "{party} से भुगतान दर्ज किया",
  "aud.udhaar.settle": "{party} का हिसाब निपटाया",
  "aud.udhaar.claim_confirmed": "{party} के भुगतान की पुष्टि की",
  "aud.udhaar.claim_rejected": "{party} का भुगतान दावा अस्वीकार किया",
  "aud.udhaar.delete": "{party} की उधार एंट्री हटाई",
  "aud.passport.create": "{label} के लिए क्रेडिट पासपोर्ट बनाया",
  "aud.passport.revoke": "क्रेडिट पासपोर्ट रद्द किया",
  "aud.settings.upi": "UPI ID बदली",
  "aud.settings.weekly_report": "साप्ताहिक रिपोर्ट सेटिंग्स बदलीं",
  "aud.security.two_factor": "दो-चरणीय लॉगिन बदला",
  "aud.team.add": "{name} को टीम में जोड़ा",
  "aud.team.remove": "{name} को टीम से हटाया",
  "aud.ai.action": "DHAN AI कार्रवाई: {type}",
  "aud.loan.apply": "{lender} में आवेदन किया",
  "aud.loan.accept": "{lender} का ऑफ़र स्वीकारा",
  "aud.loan.withdraw": "{lender} का आवेदन वापस लिया",
  "aud.bot.transaction": "बॉट ने दर्ज किया: {vendor}",
  "aud.bot.undo": "बॉट ने हटाया: {vendor}",
  "aud.report.email": "साप्ताहिक रिपोर्ट ईमेल की",
  "aud.unknown": "गतिविधि",
  "ro.banner": "रीड-ओनली एक्सेस: आप सब देख सकते हैं पर कुछ बदल नहीं सकते।",
  "ro.badge": "रीड-ओनली",
  "auth.otpTitle": "अपना कोड डालें",
  "auth.otpSub": "हमने {phone} पर 6 अंकों का कोड भेजा है।",
  "auth.code": "6 अंकों का कोड",
  "auth.verify": "जांचें और साइन इन करें",
  "auth.useCode": "इसके बजाय कोड से साइन इन करें",
  "auth.usePassword": "मेरा पासवर्ड इस्तेमाल करें",
  "auth.sendCode": "मुझे कोड भेजें",
  "auth.demoNote": "डेमो मोड: आपका कोड WhatsApp या SMS से आने के बजाय यहां दिखता है।",
  "auth.demoCode": "आपका DHAN लॉगिन कोड {code} है",
  "auth.codeWrong": "कोड गलत है या समाप्त हो चुका है।",
  "auth.resend": "नया कोड भेजें",
  "auth.locked": "बहुत ज़्यादा कोशिशें। कृपया कुछ मिनट रुकें।",

  "act.title": "सुझाई गई योजना",
  "act.noteNothing": "अभी कुछ ठीक करने की ज़रूरत नहीं।",
  "act.before": "आज का सबसे निचला कैश स्तर",
  "act.after": "इस योजना के साथ",
  "act.resolves": "आपको सुरक्षा बफ़र के ऊपर रखता है",
  "act.stillTight": "अब भी सुरक्षा बफ़र से नीचे। और कदमों पर सोचें।",
  "act.assume": "मानकर चलता है कि जिन ग्राहकों को आप याद दिलाएंगे वे 4 दिन में चुकाएंगे, हर एक के भरोसे के अनुसार।",
  "act.approve": "मंज़ूर करें",
  "act.skip": "छोड़ें",
  "act.approveAll": "सब मंज़ूर करें",
  "act.done": "हो गया",
  "act.skipped": "छोड़ा गया",
  "act.failed": "विफल",
  "act.send_reminders": "{amount} बाकी वाले {n} ग्राहकों को याद दिलाएं",
  "act.delay_bill": "{party} को {from} के बजाय {to} को चुकाएं",
  "act.delay_billDetail": "{amount} आगे खिसकता है",
  "act.enable_auto_remind": "{n} इनवॉइस पर अपने-आप याद चालू करें",
  "act.result.send_reminders": "{total} में से {sent} को याद भेजी गई",
  "act.result.delay_bill": "देय तारीख {date} हुई",
  "act.result.enable_auto_remind": "{n} पर अपने-आप याद चालू",
  "act.fail": "यह नहीं हो सका। फिर कोशिश करें।",

  "rv.title": "DHAN ने वसूला",
  "rv.body": "DHAN की याद के बाद {n} इनवॉइस पर {amount} मिले",
};
