// UI copy. Keys are shared; `hi` falls back to `en` when a key is missing.
// Backend-generated text (insight bodies, forecast method names) is not translated here.

export const en = {
  // nav
  "nav.dashboard": "Dashboard",
  "nav.home": "Home",
  "nav.transactions": "Transactions",
  "nav.insights": "Insights & Alerts",
  "nav.insightsShort": "Insights",
  "nav.ledger": "Ledger",
  "nav.forecast": "Forecast",
  "nav.credit": "Credit Readiness",
  "nav.settings": "Settings",
  "nav.more": "More",
  "nav.logout": "Log out",
  "nav.add": "Add transaction",
  "nav.skip": "Skip to content",
  "nav.business": "Business",
  "nav.close": "Close",

  // common
  "common.retry": "Retry",
  "common.viewAll": "View all",
  "common.viewDetails": "View details",
  "common.live": "LIVE",
  "common.demo": "DEMO DATA",
  "common.income": "Income",
  "common.expense": "Expense",
  "common.expenses": "Expenses",
  "common.net": "Net",
  "common.cash": "Cash in hand",
  "common.vsPrev": "vs previous period",
  "common.language": "Language",
  "common.loading": "Loading…",
  "common.error": "Can't reach DHAN right now.",
  "common.errorBody": "Check your connection and try again.",
  "common.showPassword": "Show password",
  "common.hidePassword": "Hide password",
  "common.optional": "optional",

  // bands & status
  "band.EXCELLENT": "Excellent",
  "band.GOOD": "Good",
  "band.FAIR": "Fair",
  "band.NEEDS WORK": "Needs work",
  "status.HEALTHY": "Healthy",
  "status.WATCH": "Watch",
  "status.AT RISK": "At risk",

  // auth
  "auth.tagline1": "Know your money.",
  "auth.tagline2": "Grow your business.",
  "auth.sub": "Every sale and every expense, turned into a clear next step.",
  "auth.proof1": "Cash outlook for the next 30 days",
  "auth.proof2": "Spots unusual spending early",
  "auth.proof3": "An explainable credit-readiness score",
  "auth.sample": "Sample data, for illustration",
  "auth.welcome": "Welcome back",
  "auth.welcomeSub": "Log in to see where your money is going.",
  "auth.phone": "Phone number",
  "auth.password": "Password",
  "auth.login": "Log in",
  "auth.loggingIn": "Logging in…",
  "auth.newHere": "New to DHAN?",
  "auth.create": "Create an account",
  "auth.createTitle": "Create your account",
  "auth.createSub": "Takes less than a minute.",
  "auth.about": "About you",
  "auth.aboutBiz": "About your business",
  "auth.name": "Your name",
  "auth.passwordHint": "At least 6 characters",
  "auth.bizName": "Business name",
  "auth.bizType": "Business type",
  "auth.city": "City",
  "auth.opening": "Cash in hand today (₹)",
  "auth.openingHint": "Opening balance",
  "auth.creating": "Creating account…",
  "auth.createBtn": "Create account",
  "auth.haveAccount": "Already have an account?",
  "auth.regTitle1": "Set up your",
  "auth.regTitle2": "business in minutes.",
  "auth.regSub": "One place for income, expenses and the insights that matter.",
  "auth.genericError": "Something went wrong. Please try again.",
  "biz.Retail": "Retail",
  "biz.Manufacturing": "Manufacturing",
  "biz.Services": "Services",
  "biz.Wholesale/Trading": "Wholesale / Trading",
  "biz.Food & Beverage": "Food & Beverage",
  "biz.Other": "Other",

  // dashboard
  "dash.greetMorning": "Good morning",
  "dash.greetAfternoon": "Good afternoon",
  "dash.greetEvening": "Good evening",
  "dash.add": "Add transaction",
  "dash.period": "Time period",
  "dash.today": "Today",
  "dash.7d": "7 days",
  "dash.30d": "30 days",
  "dash.month": "Month",
  "dash.cashHeroLabel": "Cash in hand",
  "dash.outlook": "30-day outlook",
  "dash.pulseHealthy": "You're on track. Expected balance in 30 days: {amount}.",
  "dash.pulseWatch": "Worth watching. In a weak month your balance could fall to {amount}.",
  "dash.pulseRisk": "Heads up. At this pace your balance may drop to {amount} in 30 days.",
  "dash.pulseNone": "Add a few weeks of transactions, or load demo data in Settings, to see your outlook.",
  "dash.attention": "Needs your attention",
  "dash.allClear": "Nothing unusual right now.",
  "dash.seeInsights": "See all insights",
  "dash.trend": "Cash flow",
  "dash.trendEmpty": "No financial activity recorded.",
  "dash.trendEmptyBody": "Add your first transaction to see your cash flow.",
  "dash.mix": "Where the money goes",
  "dash.mixEmpty": "No spending yet.",
  "dash.mixEmptyBody": "Expenses you add will show up here by category.",
  "dash.vendors": "Biggest vendors",
  "dash.vendorsEmpty": "No vendors yet.",
  "dash.vendorsEmptyBody": "Your most frequent expense vendors will appear here.",
  "dash.txnCount": "{n} transactions",
  "dash.txnOne": "1 transaction",
  "dash.ofSpend": "{pct}% of spend",
  "dash.alerts": "Insights & alerts",
  "dash.alertsEmpty": "No insights yet.",
  "dash.alertsEmptyBody": "DHAN will surface patterns here once you have more activity.",
  "dash.forecast": "30-day forecast",
  "dash.noHistory": "Not enough history yet.",
  "dash.noHistoryBody": "Add transactions for a more reliable forecast.",
  "dash.expectedClose": "Expected closing balance",
  "dash.worst": "Worst case",
  "dash.best": "Best case",
  "dash.expected": "Expected",
  "dash.now": "Now",
  "dash.basedOn": "Based on your last {n} rolling periods.",
  "dash.backtest": "Backtest error: {pct}%.",
  "dash.how": "How is this calculated?",
  "dash.method": "Method",
  "dash.weights": "Weights",
  "dash.dataUsed": "Data used",
  "dash.credit": "Credit readiness",
  "dash.biggestOpp": "Biggest opportunity",
  "dash.notCibil": "An indicative score, not a CIBIL score.",
  "dash.vsLast": "vs previous period",

  // transactions
  "txn.title": "Transactions",
  "txn.net": "Net: {amount}",
  "txn.add": "Add transaction",
  "txn.search": "Search vendor…",
  "txn.allTypes": "All",
  "txn.allCategories": "All categories",
  "txn.empty": "No financial activity recorded.",
  "txn.emptyBody": "Add your first transaction to get started.",
  "txn.addFirst": "Add your first transaction",
  "txn.date": "Date",
  "txn.vendor": "Vendor",
  "txn.category": "Category",
  "txn.amount": "Amount",
  "txn.payment": "Payment",
  "txn.source": "Source",
  "txn.status": "Status",
  "txn.review": "Review",
  "txn.details": "Transaction details",
  "txn.flagged": "Flagged for review",
  "txn.paymentMode": "Payment mode",
  "txn.gstin": "GSTIN",
  "txn.description": "Description",
  "txn.delete": "Delete transaction",
  "txn.deleting": "Deleting…",
  "txn.deleted": "Transaction deleted",
  "txn.deleteFail": "Couldn't delete transaction.",
  "txn.saved": "Transaction saved",
  "txn.saveFail": "Couldn't save transaction. Try again.",
  "txn.addTitle": "Add transaction",
  "txn.manual": "Type it in",
  "txn.scan": "Scan a bill",
  "txn.vendorHint": "e.g. Laxmi Fabrics",
  "txn.gstinOpt": "GSTIN (optional)",
  "txn.descOpt": "Note (optional)",
  "txn.noteHint": "Add a note…",
  "txn.moreDetails": "More details",
  "txn.lessDetails": "Fewer details",
  "txn.save": "Save transaction",
  "txn.saving": "Saving…",
  "txn.confirm": "Confirm & save",
  "txn.scanTitle": "Scan your bill",
  "txn.scanBody": "Drag and drop an image here, or choose an option below.",
  "txn.upload": "Upload file",
  "txn.photo": "Take photo",
  "txn.enterManually": "Enter manually",
  "txn.pleaseCheck": "Please check",
  "txn.confidence": "{pct}% sure",
  "txn.ocr1": "Uploading bill",
  "txn.ocr2": "Reading document",
  "txn.ocr3": "Extracting amount",
  "txn.ocr4": "Identifying vendor",
  "txn.ocr5": "Detecting category",
  "txn.ocr6": "Ready for review",
  "pay.Cash": "Cash",
  "pay.UPI": "UPI",
  "pay.Bank Transfer": "Bank transfer",
  "pay.Card": "Card",
  "pay.Cheque": "Cheque",

  // insights
  "ins.title": "Financial intelligence",
  "ins.sub": "DHAN found these patterns in your business.",
  "ins.needs_attention": "Needs attention",
  "ins.spending_pattern": "Spending patterns",
  "ins.savings_opportunity": "Savings opportunities",
  "ins.empty": "No insights yet.",
  "ins.emptyBody": "Add more transactions and DHAN will surface patterns here.",
  "ins.expected": "This was expected",
  "ins.needsReview": "Needs review",
  "ins.method": "How we know: {method}",

  // forecast
  "fc.title": "30-day cash forecast",
  "fc.sub": "Where your balance is likely headed, and why.",
  "fc.expectedClose": "Expected closing balance",
  "fc.range": "Likely range after 30 days",
  "fc.history": "Net cash per 30-day period",
  "fc.next": "Next 30 days",
  "fc.byCategory": "Expected spend by category",
  "fc.excluding": "Excluding flagged one-offs",
  "fc.noCategory": "Not enough category history yet.",
  "fc.assumptions": "How this forecast works",
  "fc.method": "Method",
  "fc.dataUsed": "Data used",
  "fc.weights": "Weights",
  "fc.mape": "Backtest error (MAPE)",
  "fc.noMape": "Not enough history yet",
  "fc.note": "Weights apply oldest to newest across the last 3 rolling 30-day periods, plus a simple trend term.",
  "fc.legendPast": "Past periods",
  "fc.legendLoss": "Loss-making period",
  "fc.legendForecast": "Forecast",

  // credit
  "cr.title": "Credit readiness",
  "cr.sub": "A financial health report built entirely from your own records.",
  "cr.blend": "This score blends five weighted components from your last 90 days of transactions.",
  "cr.components": "What makes up your score",
  "cr.weight": "weight {pct}%",
  "cr.opp": "Your biggest opportunity",
  "cr.outOf": "out of 100",

  // settings
  "set.title": "Settings",
  "set.sub": "Your profile, language and data.",
  "set.profile": "Profile",
  "set.owner": "Owner",
  "set.phone": "Phone",
  "set.business": "Business",
  "set.type": "Type",
  "set.city": "City",
  "set.language": "Language",
  "set.languageBody": "Choose the language for menus and labels. Insight explanations stay in English for now.",
  "set.demo": "Demo data",
  "set.demoBody":
    "Load about 180 days of realistic sample history, tagged DEMO DATA, so the dashboard, insights, forecast and credit score have something to show. Resetting removes only demo data; your own LIVE transactions are never touched.",
  "set.load": "Load demo data",
  "set.loading": "Loading…",
  "set.reset": "Reset demo data",
  "set.resetting": "Resetting…",
  "set.loaded": "Loaded {n} demo transactions",
  "set.loadFail": "Couldn't load demo data.",
  "set.resetDone": "Demo data reset",
  "set.resetFail": "Couldn't reset demo data.",
  "set.export": "Export your data",
  "set.exportBody": "Download every transaction as a CSV file you can open in Excel or share with your accountant.",
  "set.exportBtn": "Download CSV",
  "set.exported": "Exported {n} transactions",
  "set.exportFail": "Couldn't export your data.",
  "set.session": "Session",
  "set.logout": "Log out of this device",

  // categories (display only; stored values stay English)
  "cat.Raw Material & Stock": "Raw Material & Stock",
  "cat.Salaries & Wages": "Salaries & Wages",
  "cat.Rent": "Rent",
  "cat.Utilities": "Utilities",
  "cat.Transport & Fuel": "Transport & Fuel",
  "cat.Food & Refreshments": "Food & Refreshments",
  "cat.Marketing": "Marketing",
  "cat.Repairs & Maintenance": "Repairs & Maintenance",
  "cat.Taxes & Fees": "Taxes & Fees",
  "cat.Others": "Others",
  "cat.Sales Revenue": "Sales Revenue",
  "cat.Services Rendered": "Services Rendered",
  "cat.Other Income": "Other Income",
};

export const hi = {
  "nav.dashboard": "डैशबोर्ड",
  "nav.home": "होम",
  "nav.transactions": "लेन-देन",
  "nav.insights": "इनसाइट्स और अलर्ट",
  "nav.insightsShort": "इनसाइट्स",
  "nav.ledger": "खाता",
  "nav.forecast": "पूर्वानुमान",
  "nav.credit": "क्रेडिट तैयारी",
  "nav.settings": "सेटिंग्स",
  "nav.more": "और",
  "nav.logout": "लॉग आउट",
  "nav.add": "लेन-देन जोड़ें",
  "nav.skip": "मुख्य सामग्री पर जाएं",
  "nav.business": "व्यापार",
  "nav.close": "बंद करें",

  "common.retry": "फिर कोशिश करें",
  "common.viewAll": "सभी देखें",
  "common.viewDetails": "विवरण देखें",
  "common.live": "लाइव",
  "common.demo": "डेमो डेटा",
  "common.income": "आमदनी",
  "common.expense": "खर्च",
  "common.expenses": "खर्चे",
  "common.net": "शुद्ध बचत",
  "common.cash": "हाथ में नकद",
  "common.vsPrev": "पिछली अवधि से",
  "common.language": "भाषा",
  "common.loading": "लोड हो रहा है…",
  "common.error": "अभी DHAN से संपर्क नहीं हो पा रहा।",
  "common.errorBody": "इंटरनेट जांचें और फिर कोशिश करें।",
  "common.showPassword": "पासवर्ड दिखाएं",
  "common.hidePassword": "पासवर्ड छिपाएं",
  "common.optional": "वैकल्पिक",

  "band.EXCELLENT": "उत्कृष्ट",
  "band.GOOD": "अच्छा",
  "band.FAIR": "ठीक-ठाक",
  "band.NEEDS WORK": "सुधार चाहिए",
  "status.HEALTHY": "स्वस्थ",
  "status.WATCH": "नज़र रखें",
  "status.AT RISK": "जोखिम में",

  "auth.tagline1": "अपना पैसा जानिए।",
  "auth.tagline2": "अपना व्यापार बढ़ाइए।",
  "auth.sub": "हर बिक्री और हर खर्च, एक साफ़ अगले कदम में।",
  "auth.proof1": "अगले 30 दिनों का कैश अनुमान",
  "auth.proof2": "असामान्य खर्च की जल्दी पहचान",
  "auth.proof3": "समझ में आने वाला क्रेडिट-तैयारी स्कोर",
  "auth.sample": "उदाहरण के लिए नमूना डेटा",
  "auth.welcome": "वापसी पर स्वागत है",
  "auth.welcomeSub": "लॉग इन करके देखें कि आपका पैसा कहां जा रहा है।",
  "auth.phone": "फ़ोन नंबर",
  "auth.password": "पासवर्ड",
  "auth.login": "लॉग इन करें",
  "auth.loggingIn": "लॉग इन हो रहा है…",
  "auth.newHere": "DHAN पर नए हैं?",
  "auth.create": "खाता बनाएं",
  "auth.createTitle": "अपना खाता बनाएं",
  "auth.createSub": "एक मिनट से भी कम समय लगेगा।",
  "auth.about": "आपके बारे में",
  "auth.aboutBiz": "आपके व्यापार के बारे में",
  "auth.name": "आपका नाम",
  "auth.passwordHint": "कम से कम 6 अक्षर",
  "auth.bizName": "व्यापार का नाम",
  "auth.bizType": "व्यापार का प्रकार",
  "auth.city": "शहर",
  "auth.opening": "आज हाथ में नकद (₹)",
  "auth.openingHint": "शुरुआती बैलेंस",
  "auth.creating": "खाता बन रहा है…",
  "auth.createBtn": "खाता बनाएं",
  "auth.haveAccount": "पहले से खाता है?",
  "auth.regTitle1": "अपना व्यापार",
  "auth.regTitle2": "मिनटों में शुरू करें।",
  "auth.regSub": "आमदनी, खर्च और काम की जानकारी, सब एक जगह।",
  "auth.genericError": "कुछ गड़बड़ हो गई। कृपया फिर कोशिश करें।",
  "biz.Retail": "खुदरा",
  "biz.Manufacturing": "निर्माण",
  "biz.Services": "सेवाएं",
  "biz.Wholesale/Trading": "थोक / व्यापार",
  "biz.Food & Beverage": "खान-पान",
  "biz.Other": "अन्य",

  "dash.greetMorning": "सुप्रभात",
  "dash.greetAfternoon": "नमस्कार",
  "dash.greetEvening": "शुभ संध्या",
  "dash.add": "लेन-देन जोड़ें",
  "dash.period": "समय अवधि",
  "dash.today": "आज",
  "dash.7d": "7 दिन",
  "dash.30d": "30 दिन",
  "dash.month": "महीना",
  "dash.cashHeroLabel": "हाथ में नकद",
  "dash.outlook": "30 दिन का अनुमान",
  "dash.pulseHealthy": "सब ठीक चल रहा है। 30 दिन बाद अनुमानित बैलेंस: {amount}।",
  "dash.pulseWatch": "नज़र रखें। कमज़ोर महीने में आपका बैलेंस {amount} तक गिर सकता है।",
  "dash.pulseRisk": "सावधान। इसी रफ़्तार से 30 दिन में बैलेंस {amount} तक गिर सकता है।",
  "dash.pulseNone": "अनुमान देखने के लिए कुछ हफ़्तों के लेन-देन जोड़ें, या सेटिंग्स में डेमो डेटा लोड करें।",
  "dash.attention": "आपका ध्यान चाहिए",
  "dash.allClear": "अभी कुछ असामान्य नहीं है।",
  "dash.seeInsights": "सभी इनसाइट्स देखें",
  "dash.trend": "कैश फ़्लो",
  "dash.trendEmpty": "अभी कोई लेन-देन दर्ज नहीं है।",
  "dash.trendEmptyBody": "अपना कैश फ़्लो देखने के लिए पहला लेन-देन जोड़ें।",
  "dash.mix": "पैसा कहां जाता है",
  "dash.mixEmpty": "अभी कोई खर्च नहीं।",
  "dash.mixEmptyBody": "आप जो खर्च जोड़ेंगे वे श्रेणी के अनुसार यहां दिखेंगे।",
  "dash.vendors": "सबसे बड़े विक्रेता",
  "dash.vendorsEmpty": "अभी कोई विक्रेता नहीं।",
  "dash.vendorsEmptyBody": "सबसे ज़्यादा खर्च वाले विक्रेता यहां दिखेंगे।",
  "dash.txnCount": "{n} लेन-देन",
  "dash.txnOne": "1 लेन-देन",
  "dash.ofSpend": "खर्च का {pct}%",
  "dash.alerts": "इनसाइट्स और अलर्ट",
  "dash.alertsEmpty": "अभी कोई इनसाइट नहीं।",
  "dash.alertsEmptyBody": "ज़्यादा गतिविधि होने पर DHAN यहां पैटर्न दिखाएगा।",
  "dash.forecast": "30 दिन का पूर्वानुमान",
  "dash.noHistory": "अभी पर्याप्त इतिहास नहीं है।",
  "dash.noHistoryBody": "बेहतर पूर्वानुमान के लिए और लेन-देन जोड़ें।",
  "dash.expectedClose": "अनुमानित अंतिम बैलेंस",
  "dash.worst": "सबसे बुरा हाल",
  "dash.best": "सबसे अच्छा हाल",
  "dash.expected": "अनुमानित",
  "dash.now": "अभी",
  "dash.basedOn": "आपकी पिछली {n} अवधियों पर आधारित।",
  "dash.backtest": "बैकटेस्ट त्रुटि: {pct}%।",
  "dash.how": "यह कैसे निकाला गया?",
  "dash.method": "तरीका",
  "dash.weights": "भार",
  "dash.dataUsed": "इस्तेमाल किया डेटा",
  "dash.credit": "क्रेडिट तैयारी",
  "dash.biggestOpp": "सबसे बड़ा मौका",
  "dash.notCibil": "यह सांकेतिक स्कोर है, CIBIL स्कोर नहीं।",
  "dash.vsLast": "पिछली अवधि से",

  "txn.title": "लेन-देन",
  "txn.net": "शुद्ध: {amount}",
  "txn.add": "लेन-देन जोड़ें",
  "txn.search": "विक्रेता खोजें…",
  "txn.allTypes": "सभी",
  "txn.allCategories": "सभी श्रेणियां",
  "txn.empty": "अभी कोई लेन-देन दर्ज नहीं है।",
  "txn.emptyBody": "शुरू करने के लिए पहला लेन-देन जोड़ें।",
  "txn.addFirst": "पहला लेन-देन जोड़ें",
  "txn.date": "तारीख",
  "txn.vendor": "विक्रेता",
  "txn.category": "श्रेणी",
  "txn.amount": "राशि",
  "txn.payment": "भुगतान",
  "txn.source": "स्रोत",
  "txn.status": "स्थिति",
  "txn.review": "जांचें",
  "txn.details": "लेन-देन का विवरण",
  "txn.flagged": "जांच के लिए चिह्नित",
  "txn.paymentMode": "भुगतान का तरीका",
  "txn.gstin": "GSTIN",
  "txn.description": "विवरण",
  "txn.delete": "लेन-देन हटाएं",
  "txn.deleting": "हटाया जा रहा है…",
  "txn.deleted": "लेन-देन हटा दिया गया",
  "txn.deleteFail": "लेन-देन नहीं हटा सके।",
  "txn.saved": "लेन-देन सहेजा गया",
  "txn.saveFail": "लेन-देन नहीं सहेज सके। फिर कोशिश करें।",
  "txn.addTitle": "लेन-देन जोड़ें",
  "txn.manual": "खुद लिखें",
  "txn.scan": "बिल स्कैन करें",
  "txn.vendorHint": "जैसे लक्ष्मी फ़ैब्रिक्स",
  "txn.gstinOpt": "GSTIN (वैकल्पिक)",
  "txn.descOpt": "नोट (वैकल्पिक)",
  "txn.noteHint": "नोट जोड़ें…",
  "txn.moreDetails": "और विवरण",
  "txn.lessDetails": "कम विवरण",
  "txn.save": "लेन-देन सहेजें",
  "txn.saving": "सहेजा जा रहा है…",
  "txn.confirm": "पुष्टि करें और सहेजें",
  "txn.scanTitle": "अपना बिल स्कैन करें",
  "txn.scanBody": "तस्वीर यहां खींचकर छोड़ें, या नीचे से चुनें।",
  "txn.upload": "फ़ाइल अपलोड करें",
  "txn.photo": "फ़ोटो खींचें",
  "txn.enterManually": "खुद दर्ज करें",
  "txn.pleaseCheck": "कृपया जांचें",
  "txn.confidence": "{pct}% पक्का",
  "txn.ocr1": "बिल अपलोड हो रहा है",
  "txn.ocr2": "दस्तावेज़ पढ़ा जा रहा है",
  "txn.ocr3": "राशि निकाली जा रही है",
  "txn.ocr4": "विक्रेता पहचाना जा रहा है",
  "txn.ocr5": "श्रेणी तय हो रही है",
  "txn.ocr6": "जांच के लिए तैयार",
  "pay.Cash": "नकद",
  "pay.UPI": "UPI",
  "pay.Bank Transfer": "बैंक ट्रांसफ़र",
  "pay.Card": "कार्ड",
  "pay.Cheque": "चेक",

  "ins.title": "वित्तीय जानकारी",
  "ins.sub": "DHAN को आपके व्यापार में ये पैटर्न मिले।",
  "ins.needs_attention": "ध्यान चाहिए",
  "ins.spending_pattern": "खर्च के पैटर्न",
  "ins.savings_opportunity": "बचत के मौके",
  "ins.empty": "अभी कोई इनसाइट नहीं।",
  "ins.emptyBody": "और लेन-देन जोड़ें, DHAN यहां पैटर्न दिखाएगा।",
  "ins.expected": "यह अपेक्षित था",
  "ins.needsReview": "जांच चाहिए",
  "ins.method": "कैसे पता चला: {method}",

  "fc.title": "30 दिन का कैश पूर्वानुमान",
  "fc.sub": "आपका बैलेंस किस ओर जा रहा है, और क्यों।",
  "fc.expectedClose": "अनुमानित अंतिम बैलेंस",
  "fc.range": "30 दिन बाद संभावित दायरा",
  "fc.history": "हर 30 दिन की शुद्ध नकदी",
  "fc.next": "अगले 30 दिन",
  "fc.byCategory": "श्रेणी के अनुसार अनुमानित खर्च",
  "fc.excluding": "चिह्नित एक-बारगी खर्च छोड़कर",
  "fc.noCategory": "श्रेणी का पर्याप्त इतिहास नहीं है।",
  "fc.assumptions": "यह पूर्वानुमान कैसे बनता है",
  "fc.method": "तरीका",
  "fc.dataUsed": "इस्तेमाल किया डेटा",
  "fc.weights": "भार",
  "fc.mape": "बैकटेस्ट त्रुटि (MAPE)",
  "fc.noMape": "अभी पर्याप्त इतिहास नहीं है",
  "fc.note": "भार पिछली 3 अवधियों पर पुरानी से नई के क्रम में लगते हैं, साथ में एक सरल ट्रेंड जोड़ा जाता है।",
  "fc.legendPast": "पिछली अवधियां",
  "fc.legendLoss": "घाटे वाली अवधि",
  "fc.legendForecast": "पूर्वानुमान",

  "cr.title": "क्रेडिट तैयारी",
  "cr.sub": "पूरी तरह आपके अपने रिकॉर्ड से बनी वित्तीय सेहत की रिपोर्ट।",
  "cr.blend": "यह स्कोर पिछले 90 दिनों के लेन-देन के पांच भारित हिस्सों से बनता है।",
  "cr.components": "आपका स्कोर किससे बना है",
  "cr.weight": "भार {pct}%",
  "cr.opp": "आपका सबसे बड़ा मौका",
  "cr.outOf": "100 में से",

  "set.title": "सेटिंग्स",
  "set.sub": "आपकी प्रोफ़ाइल, भाषा और डेटा।",
  "set.profile": "प्रोफ़ाइल",
  "set.owner": "मालिक",
  "set.phone": "फ़ोन",
  "set.business": "व्यापार",
  "set.type": "प्रकार",
  "set.city": "शहर",
  "set.language": "भाषा",
  "set.languageBody": "मेनू और लेबल की भाषा चुनें। इनसाइट्स की व्याख्या अभी अंग्रेज़ी में ही रहेगी।",
  "set.demo": "डेमो डेटा",
  "set.demoBody":
    "लगभग 180 दिनों का असली जैसा नमूना इतिहास लोड करें (डेमो डेटा के रूप में चिह्नित), ताकि डैशबोर्ड, इनसाइट्स, पूर्वानुमान और क्रेडिट स्कोर में कुछ दिखे। रीसेट करने पर केवल डेमो डेटा हटता है; आपके अपने लाइव लेन-देन कभी नहीं छुए जाते।",
  "set.load": "डेमो डेटा लोड करें",
  "set.loading": "लोड हो रहा है…",
  "set.reset": "डेमो डेटा रीसेट करें",
  "set.resetting": "रीसेट हो रहा है…",
  "set.loaded": "{n} डेमो लेन-देन लोड हुए",
  "set.loadFail": "डेमो डेटा लोड नहीं हो सका।",
  "set.resetDone": "डेमो डेटा रीसेट हो गया",
  "set.resetFail": "डेमो डेटा रीसेट नहीं हो सका।",
  "set.export": "अपना डेटा निकालें",
  "set.exportBody": "हर लेन-देन को CSV फ़ाइल के रूप में डाउनलोड करें, जिसे आप Excel में खोल सकते हैं या अपने अकाउंटेंट को भेज सकते हैं।",
  "set.exportBtn": "CSV डाउनलोड करें",
  "set.exported": "{n} लेन-देन निकाले गए",
  "set.exportFail": "आपका डेटा नहीं निकाल सके।",
  "set.session": "सत्र",
  "set.logout": "इस डिवाइस से लॉग आउट करें",

  "cat.Raw Material & Stock": "कच्चा माल और स्टॉक",
  "cat.Salaries & Wages": "वेतन और मज़दूरी",
  "cat.Rent": "किराया",
  "cat.Utilities": "बिजली-पानी आदि",
  "cat.Transport & Fuel": "परिवहन और ईंधन",
  "cat.Food & Refreshments": "खान-पान",
  "cat.Marketing": "प्रचार",
  "cat.Repairs & Maintenance": "मरम्मत और रखरखाव",
  "cat.Taxes & Fees": "कर और शुल्क",
  "cat.Others": "अन्य",
  "cat.Sales Revenue": "बिक्री से आमदनी",
  "cat.Services Rendered": "सेवाओं से आमदनी",
  "cat.Other Income": "अन्य आमदनी",
};
