// Copy for voice entry, statement import, receivables, what-if simulator and the Credit Passport.

export const enWow = {
  "nav.receivables": "Receivables",

  // voice
  "voice.tab": "Speak",
  "voice.tap": "Tap and speak",
  "voice.stop": "Tap to stop",
  "voice.listening": "Listening…",
  "voice.speakIn": "Speaking in",
  "voice.example.en": "Paid 500 to Sharma Transport for petrol by UPI",
  "voice.example.hi": "शर्मा ट्रांसपोर्ट को 500 रुपये दिए",
  "voice.example.mr": "सुनील कडून 2500 रुपये मिळाले",
  "voice.typeInstead": "Or type it like you'd say it",
  "voice.typePlaceholder": "e.g. Paid 500 to Sharma Transport for petrol",
  "voice.understand": "Fill the form",
  "voice.unsupported": "Voice input isn't available in this browser. Type a sentence below instead.",
  "voice.blocked": "Microphone access was blocked. Allow it in your browser, or type below.",
  "voice.heard": "We heard",
  "voice.again": "Try again",
  "voice.check": "Check the details before saving.",
  "voice.noAmount": "We couldn't hear an amount. Please fill it in.",

  // statement import
  "imp.btn": "Import statement",
  "imp.title": "Import a bank statement",
  "imp.body": "Upload your bank statement as a CSV. DHAN reads dates, amounts and narrations, guesses the category, and you check everything before it is added.",
  "imp.choose": "Choose CSV file",
  "imp.drop": "or drop it here",
  "imp.sample": "Download a sample statement",
  "imp.errHeader": "We couldn't find dates and amounts in this file. Export the statement as CSV from your bank and try again.",
  "imp.errEmpty": "No transactions were found in this file.",
  "imp.found": "{n} transactions found",
  "imp.range": "{from} to {to}",
  "imp.review": "Check the categories. Anything already in DHAN is skipped, so re-importing is safe.",
  "imp.skippedLines": "{n} lines had no date or amount and were left out.",
  "imp.go": "Import {n} transactions",
  "imp.importing": "Importing…",
  "imp.done": "Imported {imported}, skipped {skipped} duplicates",
  "imp.fail": "Import failed. Please try again.",
  "imp.back": "Choose a different file",
  "imp.in": "Money in",
  "imp.out": "Money out",

  // receivables
  "rec.title": "Receivables & payables",
  "rec.sub": "Who owes you, and whom you owe. Get paid faster.",
  "rec.owedToMe": "Owed to you",
  "rec.iOwe": "You owe",
  "rec.overdue": "{amount} overdue",
  "rec.noneOverdue": "Nothing overdue",
  "rec.aging": "How late is it?",
  "rec.b.current": "Not due yet",
  "rec.b.d1_30": "1–30 days late",
  "rec.b.d31_60": "31–60 days late",
  "rec.b.d61_plus": "60+ days late",
  "rec.add": "Add entry",
  "rec.kindReceivable": "Someone owes me",
  "rec.kindPayable": "I owe someone",
  "rec.party": "Name",
  "rec.partyHint": "e.g. Kalyani Tech Park",
  "rec.phone": "WhatsApp number (optional)",
  "rec.amount": "Amount",
  "rec.due": "Due date",
  "rec.note": "Note (optional)",
  "rec.save": "Save entry",
  "rec.saved": "Entry added",
  "rec.tabIn": "Owed to you",
  "rec.tabOut": "You owe",
  "rec.dueOn": "Due {date}",
  "rec.late": "{n} days late",
  "rec.remind": "Remind on WhatsApp",
  "rec.markIn": "Mark received",
  "rec.markOut": "Mark paid",
  "rec.settledIn": "Marked received. Cash updated.",
  "rec.settledOut": "Marked paid. Cash updated.",
  "rec.delete": "Delete",
  "rec.empty": "Nothing here yet.",
  "rec.emptyBody": "Add an invoice or a bill you're waiting on, and DHAN will track when it's late.",
  "rec.paid": "Settled",
  "rec.msg": "Namaste {party}, a gentle reminder from {business}: ₹{amount} was due on {date}. Please share the payment when convenient. Thank you!",

  // what-if
  "wi.title": "What if…?",
  "wi.sub": "Try a scenario and watch your 30-day cash move.",
  "wi.sales": "Sales",
  "wi.costs": "Costs",
  "wi.oneTime": "One-time cash",
  "wi.oneTimeHint": "Loan or grant in (+), equipment or deposit out (−)",
  "wi.today": "Today's forecast",
  "wi.with": "With your changes",
  "wi.diffUp": "{amount} better than the forecast",
  "wi.diffDown": "{amount} worse than the forecast",
  "wi.same": "Same as the forecast",
  "wi.runway": "If every month looked like this, your cash would last about {n} months.",
  "wi.growing": "At this pace your cash keeps growing.",
  "wi.reset": "Reset",
  "wi.p.slow": "Slow month",
  "wi.p.festive": "Festive push",
  "wi.p.loan": "₹10L loan",
  "wi.p.equip": "Buy equipment",
  "wi.expected": "Expected balance in 30 days",

  // credit passport
  "pp.title": "Credit Passport",
  "pp.sub": "Share a verified snapshot with a lender. You stay in control and can revoke it any time.",
  "pp.for": "Who is it for?",
  "pp.forHint": "e.g. HDFC Bank, Baner branch",
  "pp.valid": "Valid for",
  "pp.days": "{n} days",
  "pp.create": "Create passport link",
  "pp.creating": "Creating…",
  "pp.consent": "A lender sees your score, 90-day totals and forecast status. Individual transactions are never shared.",
  "pp.links": "Links you've shared",
  "pp.active": "Active until {date}",
  "pp.expired": "Expired",
  "pp.revoked": "Revoked",
  "pp.views": "{n} views",
  "pp.copy": "Copy link",
  "pp.copied": "Link copied",
  "pp.whatsapp": "WhatsApp",
  "pp.qr": "QR code",
  "pp.revoke": "Revoke",
  "pp.revokedToast": "Link revoked",
  "pp.created": "Passport link created",
  "pp.msg": "Here is the verified credit passport for {business}, issued by DHAN: {url}",
  "pp.scan": "Scan to open",

  // public passport page
  "pub.verified": "Verified snapshot from DHAN",
  "pub.preparedFor": "Prepared for {name}",
  "pub.score": "Credit readiness",
  "pub.last90": "Last 90 days",
  "pub.avgMonthly": "Average monthly income",
  "pub.records": "{n} months of records",
  "pub.outlook": "30-day cash outlook",
  "pub.integrity": "Integrity code",
  "pub.validUntil": "Valid until {date}",
  "pub.print": "Print or save as PDF",
  "pub.invalid": "This link isn't valid",
  "pub.expired": "This link has expired",
  "pub.notEnough": "This business doesn't have enough history for a score yet.",
  "pub.basis": "Built from the owner's own transaction records. Indicative only.",
  "pub.home": "Learn about DHAN",
};

export const hiWow = {
  "nav.receivables": "उधार / बकाया",

  "voice.tab": "बोलकर",
  "voice.tap": "दबाएं और बोलें",
  "voice.stop": "रोकने के लिए दबाएं",
  "voice.listening": "सुन रहा हूं…",
  "voice.speakIn": "भाषा",
  "voice.example.en": "Paid 500 to Sharma Transport for petrol by UPI",
  "voice.example.hi": "शर्मा ट्रांसपोर्ट को 500 रुपये दिए",
  "voice.example.mr": "सुनील कडून 2500 रुपये मिळाले",
  "voice.typeInstead": "या वैसे ही लिखें जैसे बोलते हैं",
  "voice.typePlaceholder": "जैसे: शर्मा ट्रांसपोर्ट को 500 रुपये दिए",
  "voice.understand": "फ़ॉर्म भरें",
  "voice.unsupported": "इस ब्राउज़र में बोलकर एंट्री उपलब्ध नहीं है। नीचे वाक्य लिख दें।",
  "voice.blocked": "माइक्रोफ़ोन की अनुमति नहीं मिली। ब्राउज़र में अनुमति दें, या नीचे लिखें।",
  "voice.heard": "हमने सुना",
  "voice.again": "फिर कोशिश करें",
  "voice.check": "सहेजने से पहले विवरण जांच लें।",
  "voice.noAmount": "राशि सुनाई नहीं दी। कृपया भर दें।",

  "imp.btn": "स्टेटमेंट इंपोर्ट करें",
  "imp.title": "बैंक स्टेटमेंट इंपोर्ट करें",
  "imp.body": "अपना बैंक स्टेटमेंट CSV में अपलोड करें। DHAN तारीख, राशि और विवरण पढ़कर श्रेणी का अनुमान लगाता है, और जोड़ने से पहले आप सब जांच सकते हैं।",
  "imp.choose": "CSV फ़ाइल चुनें",
  "imp.drop": "या यहां छोड़ें",
  "imp.sample": "नमूना स्टेटमेंट डाउनलोड करें",
  "imp.errHeader": "इस फ़ाइल में तारीख और राशि नहीं मिली। अपने बैंक से स्टेटमेंट CSV में निकालकर फिर कोशिश करें।",
  "imp.errEmpty": "इस फ़ाइल में कोई लेन-देन नहीं मिला।",
  "imp.found": "{n} लेन-देन मिले",
  "imp.range": "{from} से {to}",
  "imp.review": "श्रेणियां जांच लें। जो DHAN में पहले से है उसे छोड़ दिया जाता है, इसलिए दोबारा इंपोर्ट करना सुरक्षित है।",
  "imp.skippedLines": "{n} पंक्तियों में तारीख या राशि नहीं थी, उन्हें छोड़ दिया गया।",
  "imp.go": "{n} लेन-देन इंपोर्ट करें",
  "imp.importing": "इंपोर्ट हो रहा है…",
  "imp.done": "{imported} इंपोर्ट हुए, {skipped} दोहराव छोड़े गए",
  "imp.fail": "इंपोर्ट नहीं हो सका। कृपया फिर कोशिश करें।",
  "imp.back": "दूसरी फ़ाइल चुनें",
  "imp.in": "आया पैसा",
  "imp.out": "गया पैसा",

  "rec.title": "बकाया और देनदारी",
  "rec.sub": "आपको किससे लेना है, और किसे देना है। जल्दी वसूली करें।",
  "rec.owedToMe": "आपको मिलना है",
  "rec.iOwe": "आपको देना है",
  "rec.overdue": "{amount} की देरी",
  "rec.noneOverdue": "कुछ भी देर से नहीं",
  "rec.aging": "कितनी देरी है?",
  "rec.b.current": "अभी देय नहीं",
  "rec.b.d1_30": "1–30 दिन देर",
  "rec.b.d31_60": "31–60 दिन देर",
  "rec.b.d61_plus": "60+ दिन देर",
  "rec.add": "एंट्री जोड़ें",
  "rec.kindReceivable": "किसी से लेना है",
  "rec.kindPayable": "किसी को देना है",
  "rec.party": "नाम",
  "rec.partyHint": "जैसे कल्याणी टेक पार्क",
  "rec.phone": "WhatsApp नंबर (वैकल्पिक)",
  "rec.amount": "राशि",
  "rec.due": "देय तारीख",
  "rec.note": "नोट (वैकल्पिक)",
  "rec.save": "एंट्री सहेजें",
  "rec.saved": "एंट्री जुड़ गई",
  "rec.tabIn": "आपको मिलना है",
  "rec.tabOut": "आपको देना है",
  "rec.dueOn": "देय {date}",
  "rec.late": "{n} दिन देर",
  "rec.remind": "WhatsApp पर याद दिलाएं",
  "rec.markIn": "मिल गया",
  "rec.markOut": "चुका दिया",
  "rec.settledIn": "प्राप्त के रूप में दर्ज। नकद अपडेट हुआ।",
  "rec.settledOut": "भुगतान के रूप में दर्ज। नकद अपडेट हुआ।",
  "rec.delete": "हटाएं",
  "rec.empty": "अभी यहां कुछ नहीं है।",
  "rec.emptyBody": "जिस इनवॉइस या बिल का इंतज़ार है उसे जोड़ें, DHAN देरी पर नज़र रखेगा।",
  "rec.paid": "निपटाया",
  "rec.msg": "नमस्ते {party}, {business} की ओर से याद दिलाना: ₹{amount} का भुगतान {date} को देय था। कृपया सुविधा से भुगतान कर दें। धन्यवाद!",

  "wi.title": "अगर ऐसा हुआ तो…?",
  "wi.sub": "कोई परिस्थिति आज़माएं और देखें 30 दिन का कैश कैसे बदलता है।",
  "wi.sales": "बिक्री",
  "wi.costs": "खर्चे",
  "wi.oneTime": "एकबारगी रकम",
  "wi.oneTimeHint": "लोन या अनुदान आया (+), उपकरण या जमा गया (−)",
  "wi.today": "आज का पूर्वानुमान",
  "wi.with": "आपके बदलाव के साथ",
  "wi.diffUp": "पूर्वानुमान से {amount} बेहतर",
  "wi.diffDown": "पूर्वानुमान से {amount} कम",
  "wi.same": "पूर्वानुमान जैसा ही",
  "wi.runway": "अगर हर महीना ऐसा रहा, तो आपका नकद लगभग {n} महीने चलेगा।",
  "wi.growing": "इस रफ़्तार से आपका नकद बढ़ता रहेगा।",
  "wi.reset": "रीसेट",
  "wi.p.slow": "सुस्त महीना",
  "wi.p.festive": "त्योहारी धमाका",
  "wi.p.loan": "₹10 लाख का लोन",
  "wi.p.equip": "उपकरण खरीदें",
  "wi.expected": "30 दिन बाद अनुमानित बैलेंस",

  "pp.title": "क्रेडिट पासपोर्ट",
  "pp.sub": "सत्यापित जानकारी किसी ऋणदाता से साझा करें। नियंत्रण आपके हाथ में है, कभी भी रद्द करें।",
  "pp.for": "किसके लिए?",
  "pp.forHint": "जैसे HDFC बैंक, बाणेर शाखा",
  "pp.valid": "वैधता",
  "pp.days": "{n} दिन",
  "pp.create": "पासपोर्ट लिंक बनाएं",
  "pp.creating": "बन रहा है…",
  "pp.consent": "ऋणदाता आपका स्कोर, 90 दिन के कुल आंकड़े और पूर्वानुमान की स्थिति देखता है। अलग-अलग लेन-देन कभी साझा नहीं होते।",
  "pp.links": "आपके साझा किए लिंक",
  "pp.active": "{date} तक सक्रिय",
  "pp.expired": "समाप्त",
  "pp.revoked": "रद्द",
  "pp.views": "{n} बार देखा गया",
  "pp.copy": "लिंक कॉपी करें",
  "pp.copied": "लिंक कॉपी हो गया",
  "pp.whatsapp": "WhatsApp",
  "pp.qr": "QR कोड",
  "pp.revoke": "रद्द करें",
  "pp.revokedToast": "लिंक रद्द कर दिया गया",
  "pp.created": "पासपोर्ट लिंक बन गया",
  "pp.msg": "{business} का DHAN द्वारा जारी सत्यापित क्रेडिट पासपोर्ट: {url}",
  "pp.scan": "खोलने के लिए स्कैन करें",

  "pub.verified": "DHAN की ओर से सत्यापित जानकारी",
  "pub.preparedFor": "{name} के लिए तैयार",
  "pub.score": "क्रेडिट तैयारी",
  "pub.last90": "पिछले 90 दिन",
  "pub.avgMonthly": "औसत मासिक आमदनी",
  "pub.records": "{n} महीनों का रिकॉर्ड",
  "pub.outlook": "30 दिन का कैश अनुमान",
  "pub.integrity": "सत्यापन कोड",
  "pub.validUntil": "{date} तक मान्य",
  "pub.print": "प्रिंट करें या PDF सहेजें",
  "pub.invalid": "यह लिंक मान्य नहीं है",
  "pub.expired": "यह लिंक समाप्त हो चुका है",
  "pub.notEnough": "इस व्यापार का इतिहास अभी स्कोर के लिए पर्याप्त नहीं है।",
  "pub.basis": "मालिक के अपने लेन-देन रिकॉर्ड से बना। केवल सांकेतिक।",
  "pub.home": "DHAN के बारे में जानें",
};
