// Bank sync, Profit Coach, customer portal, and the owner-side pieces that talk to customers.

export const enV4 = {
  "nav.bank": "Bank sync",
  "nav.advisor": "Profit Coach",

  // ---- Bank sync
  "bk.title": "Bank sync",
  "bk.sub": "Connect your bank once. Every payment in and out lands in DHAN by itself.",
  "bk.sandbox": "Practice bank. It shows how the connection works without touching real money. Real banks connect through India's Account Aggregator system.",
  "bk.pick": "Choose your bank",
  "bk.consent": "What you are allowing",
  "bk.scope1": "Read your account details: name, masked number, balance",
  "bk.scope2": "Read your transactions, nothing else",
  "bk.scope3": "Valid for 12 months. You can withdraw it any time",
  "bk.safe": "DHAN can never move money, and never sees your PIN or password.",
  "bk.allow": "Allow and connect",
  "bk.linking": "Fetching your statement…",
  "bk.connected": "Connected",
  "bk.balance": "Bank balance",
  "bk.lastSync": "Last synced {when}",
  "bk.never": "Not synced yet",
  "bk.syncNow": "Sync now",
  "bk.syncing": "Syncing…",
  "bk.live": "Live feed",
  "bk.liveSub": "DHAN checks the bank every few seconds and adds new transactions by itself.",
  "bk.revoke": "Disconnect",
  "bk.revokeConfirm": "Disconnect this bank? Transactions already added stay in DHAN.",
  "bk.toastNew": "{n} new bank transactions added",
  "bk.toastMatched": "{party} paid {amount}. Marked against their udhaar.",
  "bk.feed": "Bank feed",
  "bk.feedSub": "Each statement line and what DHAN did with it.",
  "bk.feedEmpty": "No statement lines yet.",
  "bk.st.new": "Added",
  "bk.st.matched": "Matched to udhaar",
  "bk.st.duplicate": "Already in books",
  "bk.st.pending": "Waiting",
  "bk.app": "Bank app (practice)",
  "bk.appSub": "Move money at the bank and watch DHAN pick it up.",
  "bk.in": "Money in",
  "bk.out": "Money out",
  "bk.from": "From",
  "bk.to": "To",
  "bk.amount": "Amount",
  "bk.via": "Via",
  "bk.post": "Post at the bank",
  "bk.posted": "Posted at the bank. DHAN picks it up in a moment.",
  "bk.quick": "A customer pays an invoice",
  "bk.quickPay": "{party} pays {amount}",
  "bk.readOnly": "Only the owner can connect or change the bank.",
  "bk.count": "{n} lines",
  "bk.tag": "Bank",
  "bk.stat.in": "Money in",
  "bk.stat.out": "Money out",

  // ---- Profit Coach
  "adv.title": "Profit Coach",
  "adv.sub": "What a good CA would tell you after reading your books: where money leaks and how to earn more.",
  "adv.insufficient": "Not enough history yet",
  "adv.insufficientBody": "Add a few weeks of transactions, or connect your bank, and DHAN will study your books.",
  "adv.hero": "You could earn about {amount} more every month",
  "adv.heroSub": "From the {n} changes below, based on your last 90 days.",
  "adv.heroNone": "Your books look healthy",
  "adv.heroNoneSub": "Nothing big to fix right now. Keep an eye on the dates below.",
  "adv.profitNow": "Profit now, per month",
  "adv.profitAfter": "If you do them all",
  "adv.margin": "Margin",
  "adv.health": "Business health",
  "adv.h.strong": "Strong",
  "adv.h.steady": "Steady",
  "adv.h.needs_work": "Needs work",
  "adv.f.margin": "Profit margin",
  "adv.f.growth": "Sales growth",
  "adv.f.cost": "Cost control",
  "adv.f.collections": "Collections",
  "adv.f.runway": "Cash cushion",
  "adv.fv.margin": "{v}% of sales kept",
  "adv.fv.growth": "{v}% vs the 90 days before",
  "adv.fv.cost": "Expenses {v}% vs before",
  "adv.fv.collections": "{v}% of udhaar is overdue",
  "adv.fv.runway": "{v} months of expenses in hand",
  "adv.fv.none": "Not enough data",
  "adv.note": "DHAN AI's note",
  "adv.noteAuto": "In the last 90 days your business made {profit} profit on {revenue} of sales, a {margin}% margin. Fixing the points below could add about {gain} a month.",
  "adv.noteAutoNone": "In the last 90 days your business made {profit} profit on {revenue} of sales, a {margin}% margin. Nothing big needs fixing right now.",
  "adv.pnl": "Profit and loss, last 6 months",
  "adv.revenue": "Sales",
  "adv.expenses": "Expenses",
  "adv.profit": "Profit",
  "adv.cost": "Where your money goes",
  "adv.costSub": "Share of sales, against a rule of thumb for your kind of business. Not an audited benchmark.",
  "adv.of": "of sales",
  "adv.usual": "usual {n}%",
  "adv.over": "Above usual",
  "adv.ok": "Normal",
  "adv.under": "Below usual",
  "adv.plan": "Your action plan",
  "adv.planSub": "Tick the ones you will do and watch the effect.",
  "adv.perMonth": "+{amount} / month",
  "adv.protects": "Protects you",
  "adv.p.high": "Do first",
  "adv.p.medium": "Next",
  "adv.p.low": "When free",
  "adv.a.cost": "Cost",
  "adv.a.revenue": "Revenue",
  "adv.a.cash": "Cash",
  "adv.a.tax": "Tax",
  "adv.a.risk": "Risk",
  "adv.selected": "If you do these {n}: {amount} more a month, margin {from}% to {to}%",
  "adv.selectNone": "Tick a recommendation to see what it adds.",
  "adv.assume": "Estimates use stated assumptions: renegotiating saves about {neg}%, money stuck in late invoices costs about {carry}% a year, and a price rise keeps {churn}% of its gain.",
  "adv.breakeven": "Break-even",
  "adv.beSub": "Sales you need each month to cover fixed costs: salaries, rent and utilities.",
  "adv.beNeeded": "{amount} / month",
  "adv.beAbove": "You sell {amount} a month, {pct}% above break-even.",
  "adv.beBelow": "You sell {amount} a month, below break-even.",
  "adv.beNone": "Your costs rise with sales, so there is no fixed break-even to show.",
  "adv.calendar": "Dates not to miss",
  "adv.cal.gstr1": "GSTR-1 (sales return)",
  "adv.cal.gstr3b": "GSTR-3B (GST payment)",
  "adv.cal.tds": "TDS deposit",
  "adv.cal.advance_tax": "Advance tax instalment",
  "adv.today": "today",
  "adv.inDays": "in {n} days",
  "adv.calNote": "Assumes a monthly GST filer.",
  "adv.disclaimer": "This is guidance from your own numbers, not tax or legal advice. Confirm tax matters with your CA.",
  "adv.ask": "Ask DHAN AI",
  "adv.go.collect": "Chase invoices",
  "adv.go.itc": "Open GST helper",
  "adv.go.runway": "Cash calendar",
  "adv.go.tax_aside": "Open GST helper",
  "adv.steps": "What to do",

  "adv.cost_over.title": "Bring {category} down",
  "adv.cost_over.why": "You spent {amount} on {category}: {share}% of sales, where about {benchmark}% is usual. Trimming half the gap saves roughly {impact} a month.",
  "adv.cost_over.s1": "List every {category} payment from the last 3 months and mark what was not essential.",
  "adv.cost_over.s2": "Set a monthly limit for {category} and review it every Sunday.",
  "adv.cost_over.s3": "Get two fresh quotes for your biggest items before the next payment.",
  "adv.vendor_creep.title": "{vendor} is getting more expensive",
  "adv.vendor_creep.why": "Your average payment to {vendor} rose from {old} to {new} (+{pct}%) in the last 45 days.",
  "adv.vendor_creep.s1": "Ask {vendor} why, and ask for the old rate in writing.",
  "adv.vendor_creep.s2": "Get a quote from one other supplier and tell {vendor} you have it.",
  "adv.vendor_creep.s3": "Buy in bulk or at a fixed monthly price if that holds the rate.",
  "adv.vendor_dependence.title": "{share}% of your {category} goes to {vendor}",
  "adv.vendor_dependence.why": "You paid {vendor} {amount} in 90 days. Depending on one supplier is risky and weakens your bargaining.",
  "adv.vendor_dependence.s1": "Ask {vendor} for a volume discount. Even 3% adds up.",
  "adv.vendor_dependence.s2": "Qualify a second supplier for the same items.",
  "adv.vendor_dependence.s3": "Pay early only if they give a discount for it.",
  "adv.customer_concentration.title": "{name} is {share}% of your income",
  "adv.customer_concentration.why": "If {name} pays late or leaves, your cash takes a big hit.",
  "adv.customer_concentration.s1": "Agree payment terms and an advance with {name}.",
  "adv.customer_concentration.s2": "Aim to win two more customers of similar size this quarter.",
  "adv.customer_concentration.s3": "Keep a cash cushion equal to one month of their payments.",
  "adv.collect.title": "Collect {amount} that is overdue",
  "adv.collect.why": "{count} invoices are overdue; the oldest is {party} at {days} days. Money stuck there costs you about {impact} a month in lost interest (at 18% a year) and starves your cash.",
  "adv.collect.s1": "Send payment links to every overdue customer today. DHAN can do it in one tap.",
  "adv.collect.s2": "Offer a small discount for payment this week, and add a late fee to new invoices.",
  "adv.collect.s3": "Ask for part payment now from anyone who cannot pay in full.",
  "adv.price_rise.title": "Raise prices by 3%",
  "adv.price_rise.why": "Your margin is {margin}%, which is thin. A 3% increase adds about {gain} a month even if you lose a few customers.",
  "adv.price_rise.s1": "Raise prices for new customers and new orders first.",
  "adv.price_rise.s2": "Tell loyal customers a week ahead, with a reason.",
  "adv.price_rise.s3": "Watch repeat orders for a month before going further.",
  "adv.subscriptions.title": "{count} recurring charges to check",
  "adv.subscriptions.why": "Fixed monthly charges (such as {names}) add up to about {monthly} a month. Most businesses can drop or downgrade a tenth of these.",
  "adv.subscriptions.s1": "List what each one is for and who uses it.",
  "adv.subscriptions.s2": "Cancel anything unused. Move the rest to cheaper or annual plans.",
  "adv.subscriptions.s3": "Set a reminder to review them every quarter.",
  "adv.marketing_roi.title": "Marketing is growing faster than sales",
  "adv.marketing_roi.why": "Marketing spend grew {marketing_growth}% while sales grew {revenue_growth}%. It is now {share}% of sales.",
  "adv.marketing_roi.s1": "Track which channel brings paying customers, not clicks.",
  "adv.marketing_roi.s2": "Pause the weakest channel for two weeks and watch sales.",
  "adv.marketing_roi.s3": "Move budget to what works. Trimming a fifth saves about {impact} a month.",
  "adv.itc.title": "Claim {amount} of input tax credit",
  "adv.itc.why": "Bills from {suppliers} suppliers have no GSTIN, so about {amount} of GST you paid cannot be claimed.",
  "adv.itc.s1": "Ask each supplier for a GST invoice with their GSTIN.",
  "adv.itc.s2": "Add the GSTIN in DHAN when you record the bill.",
  "adv.itc.s3": "Give the GST helper's CA pack to your accountant.",
  "adv.spike.title": "{category} spending jumped",
  "adv.spike.why": "{category} cost {last30} in the last 30 days, against about {usual} a month before.",
  "adv.spike.s1": "Check the biggest {category} payments for mistakes or one-offs.",
  "adv.spike.s2": "If it is a new habit, set a monthly limit.",
  "adv.runway.title": "Build a cash cushion",
  "adv.runway.why": "You hold {cash}, about {months} months of expenses. Below 2 months, one slow month can hurt.",
  "adv.runway.s1": "Collect overdue invoices first.",
  "adv.runway.s2": "Move non-urgent bills back by a week. DHAN AI can plan this for you.",
  "adv.runway.s3": "Aim to keep three months of expenses in the bank.",
  "adv.tax_aside.title": "Set money aside for tax",
  "adv.tax_aside.why": "You made {profit} in the last 90 days. Keeping about {set_aside} aside avoids a shock. The next advance-tax date is {date} (in {days} days).",
  "adv.tax_aside.s1": "Move that amount to a separate account today.",
  "adv.tax_aside.s2": "Ask your CA to estimate this year's advance tax.",

  // ---- owner side of the customer connection
  "ev.msg": "{who}: {text}",
  "ev.who.owner": "You",
  "ev.who.customer": "Customer",
  "ev.pay_failed": "Customer's payment of {amount} failed: {reason}",
  "ev.dispute": "Customer raised a dispute: {reason}",
  "ev.dispute_resolved": "Dispute resolved",
  "notif.pay_failed": "{party}'s payment failed",
  "notif.pay_failedBody": "{amount} · {reason}",
  "notif.msg": "{party} sent you a message",
  "notif.dispute": "{party} disputed an invoice",
  "ud.reply": "Message the customer",
  "ud.replyPlaceholder": "Write a reply. The customer reads it in their DHAN portal.",
  "ud.replySend": "Send",
  "ud.resolve": "Mark their dispute as resolved",
  "ud.disputedChip": "Disputed",
  "ud.failedChip": "Payment failed: {reason}",
  "ud.chat": "Conversation",

  // ---- Customer portal
  "cu.hello": "Hello, {name}",
  "cu.owe": "You owe",
  "cu.across": "across {n} invoices",
  "cu.across1": "across 1 invoice",
  "cu.overdue": "{amount} is overdue",
  "cu.onTime": "Nothing overdue",
  "cu.allClear": "You owe nothing right now",
  "cu.allClearBody": "When a shop adds you to its udhaar, it shows up here with a way to pay.",
  "cu.failedBanner": "A payment did not go through",
  "cu.failedBannerBody": "No money was taken. Retry it from the invoice below.",
  "cu.shops": "Your shops",
  "cu.due": "Due {date}",
  "cu.late": "{n} days late",
  "cu.pay": "Pay now",
  "cu.view": "Details",
  "cu.paidChip": "Paid",
  "cu.promised": "You promised {date}",
  "cu.under": "Under review",
  "cu.failedChip": "Payment failed",
  "cu.settled": "Recently paid",
  "cu.activity": "Updates from shops",
  "cu.activityNone": "No updates yet.",
  "cu.act.sent": "{shop} sent you a reminder",
  "cu.act.msg": "{shop}: {text}",
  "cu.act.payment": "{shop} received your payment of {amount}",
  "cu.act.claim_confirmed": "{shop} confirmed your payment of {amount}",
  "cu.act.claim_rejected": "{shop} could not find your payment",
  "cu.act.dispute_resolved": "{shop} resolved your dispute",
  "cu.back": "Back",
  "cu.amountDue": "Amount due",
  "cu.ofTotal": "of {total}",
  "cu.lateFee": "Late fee so far: {amount}",
  "cu.paidFull": "This invoice is fully paid. Thank you.",
  "cu.failedTitle": "Your last payment failed ({reason})",
  "cu.failedBody": "No money was taken and {shop} has been told. You can try again, or tell them when you will pay.",
  "cu.retry": "Try again",
  "cu.promiseTitle": "Need more time?",
  "cu.promiseBody": "Promise a date. {shop} is told and pauses reminders until then.",
  "cu.promiseBtn": "Promise this date",
  "cu.promiseDone": "Promised. {shop} has been told.",
  "cu.messages": "Messages with {shop}",
  "cu.msgPlaceholder": "Write to the shop…",
  "cu.send": "Send",
  "cu.you": "You",
  "cu.noMessages": "No messages yet. Ask the shop anything about this invoice.",
  "cu.dispute": "This isn't right",
  "cu.disputeTitle": "What's wrong?",
  "cu.disputeSend": "Tell the shop",
  "cu.disputeNote": "The shop is told, and automatic reminders pause until they reply.",
  "cu.disputeOpen": "You raised a dispute. {shop} will reply here.",
  "cu.dr.wrong_amount": "The amount is wrong",
  "cu.dr.not_received": "I never got this service or goods",
  "cu.dr.already_paid": "I already paid",
  "cu.dr.other": "Something else",
  "cu.history": "History",
  "cu.ev.created": "Invoice created",
  "cu.ev.sent": "Reminder sent to you",
  "cu.ev.payment": "You paid {amount}",
  "cu.ev.pay_failed": "Payment failed: {reason}",
  "cu.ev.promise": "You promised {date}",
  "cu.ev.dispute": "You raised a dispute",
  "cu.ev.dispute_resolved": "Dispute resolved",
  "cu.ev.settled": "Fully paid",
  "cu.ev.claim": "You said you paid {amount}",
  "cu.ev.claim_confirmed": "Shop confirmed your payment",
  "cu.ev.claim_rejected": "Shop could not find your payment",
  "cu.ev.msg.owner": "{shop}: {text}",
  "cu.ev.msg.customer": "You: {text}",
  "cu.reason.insufficient_funds": "not enough balance",
  "cu.reason.bank_down": "bank not responding",
  "cu.reason.declined": "card declined",
  "cu.reason.cancelled": "cancelled",
  "cu.pm.title": "Pay {shop}",
  "cu.pm.amount": "Amount",
  "cu.pm.full": "Full amount",
  "cu.pm.part": "Part payment",
  "cu.pm.method": "Pay with",
  "cu.pm.upi": "UPI",
  "cu.pm.card": "Card",
  "cu.pm.netbanking": "Net banking",
  "cu.pm.sandbox": "Practice payment: no real money moves. Choose what should happen to see how DHAN handles it.",
  "cu.pm.outcome": "Practice result",
  "cu.pm.o.success": "Payment succeeds",
  "cu.pm.o.insufficient_funds": "Not enough balance",
  "cu.pm.o.bank_down": "Bank not responding",
  "cu.pm.o.declined": "Card declined",
  "cu.pm.o.cancelled": "I cancel",
  "cu.pm.go": "Pay {amount}",
  "cu.pm.processing": "Processing…",
  "cu.pm.successTitle": "Payment received",
  "cu.pm.receipt": "Receipt {id}",
  "cu.pm.left": "{amount} is still due on this invoice.",
  "cu.pm.settled": "This invoice is fully paid.",
  "cu.pm.failTitle": "Payment didn't go through",
  "cu.pm.failBody": "Reason: {reason}. No money was taken. {shop} has been told.",
  "cu.pm.other": "Use another method",
  "cu.pm.later": "Promise a date instead",
  "cu.pm.done": "Done",
  "cu.reg.title": "Pay what you owe, in one place",
  "cu.reg.sub": "See every shop that has you on udhaar. Pay, promise a date, or message them.",
  "cu.reg.name": "Your name",
  "cu.reg.why": "We verify your number so only you can see what you owe.",
  "cu.reg.sendCode": "Send code",
  "cu.reg.create": "Create account",
  "cu.reg.haveAcc": "Already registered?",
  "cu.reg.codeSub": "Enter the 6-digit code sent to {phone}.",
  "cu.reg.heading": "Customer account",
  "cu.reg.password": "Choose a password",
  "auth.customerLink": "Customer? See what you owe",
  "auth.ownerLink": "Own a business? Create a business account",
};

export const hiV4 = {
  "nav.bank": "बैंक सिंक",
  "nav.advisor": "प्रॉफिट कोच",

  "bk.title": "बैंक सिंक",
  "bk.sub": "बैंक एक बार जोड़ें। हर आमद और खर्च अपने आप DHAN में आ जाएगा।",
  "bk.sandbox": "यह प्रैक्टिस बैंक है। असली पैसे को छुए बिना दिखाता है कि कनेक्शन कैसे काम करता है। असली बैंक भारत के अकाउंट एग्रीगेटर सिस्टम से जुड़ते हैं।",
  "bk.pick": "अपना बैंक चुनें",
  "bk.consent": "आप क्या अनुमति दे रहे हैं",
  "bk.scope1": "खाते की जानकारी पढ़ना: नाम, छिपा हुआ नंबर, बैलेंस",
  "bk.scope2": "सिर्फ़ आपके लेन-देन पढ़ना, और कुछ नहीं",
  "bk.scope3": "12 महीने के लिए मान्य। कभी भी वापस ले सकते हैं",
  "bk.safe": "DHAN कभी पैसे नहीं भेज सकता और आपका PIN या पासवर्ड कभी नहीं देखता।",
  "bk.allow": "अनुमति दें और जोड़ें",
  "bk.linking": "आपका स्टेटमेंट आ रहा है…",
  "bk.connected": "जुड़ा हुआ",
  "bk.balance": "बैंक बैलेंस",
  "bk.lastSync": "आखिरी सिंक {when}",
  "bk.never": "अभी सिंक नहीं हुआ",
  "bk.syncNow": "अभी सिंक करें",
  "bk.syncing": "सिंक हो रहा है…",
  "bk.live": "लाइव फ़ीड",
  "bk.liveSub": "DHAN हर कुछ सेकंड में बैंक देखता है और नए लेन-देन अपने आप जोड़ देता है।",
  "bk.revoke": "डिस्कनेक्ट करें",
  "bk.revokeConfirm": "यह बैंक डिस्कनेक्ट करें? जो लेन-देन जुड़ चुके हैं वे DHAN में रहेंगे।",
  "bk.toastNew": "{n} नए बैंक लेन-देन जुड़े",
  "bk.toastMatched": "{party} ने {amount} चुकाए। उनके उधार में जोड़ दिया गया।",
  "bk.feed": "बैंक फ़ीड",
  "bk.feedSub": "हर स्टेटमेंट लाइन और DHAN ने उसके साथ क्या किया।",
  "bk.feedEmpty": "अभी कोई स्टेटमेंट लाइन नहीं।",
  "bk.st.new": "जोड़ा गया",
  "bk.st.matched": "उधार से मिलाया",
  "bk.st.duplicate": "पहले से खाते में",
  "bk.st.pending": "इंतज़ार में",
  "bk.app": "बैंक ऐप (प्रैक्टिस)",
  "bk.appSub": "बैंक में पैसे हिलाएं और देखें DHAN कैसे पकड़ता है।",
  "bk.in": "पैसा आया",
  "bk.out": "पैसा गया",
  "bk.from": "किससे",
  "bk.to": "किसको",
  "bk.amount": "रकम",
  "bk.via": "माध्यम",
  "bk.post": "बैंक में भेजें",
  "bk.posted": "बैंक में दर्ज हो गया। DHAN कुछ ही पल में पकड़ लेगा।",
  "bk.quick": "कोई ग्राहक इनवॉइस चुकाता है",
  "bk.quickPay": "{party} ने {amount} चुकाए",
  "bk.readOnly": "बैंक सिर्फ़ मालिक जोड़ या बदल सकता है।",
  "bk.count": "{n} लाइन",
  "bk.tag": "बैंक",
  "bk.stat.in": "पैसा आया",
  "bk.stat.out": "पैसा गया",

  "adv.title": "प्रॉफिट कोच",
  "adv.sub": "आपके खाते पढ़कर एक अच्छा CA जो कहता: पैसा कहाँ बह रहा है और कमाई कैसे बढ़ाएं।",
  "adv.insufficient": "अभी पर्याप्त इतिहास नहीं",
  "adv.insufficientBody": "कुछ हफ़्तों के लेन-देन जोड़ें या बैंक जोड़ें, फिर DHAN आपके खाते समझेगा।",
  "adv.hero": "आप हर महीने लगभग {amount} और कमा सकते हैं",
  "adv.heroSub": "नीचे के {n} बदलावों से, पिछले 90 दिनों के आधार पर।",
  "adv.heroNone": "आपके खाते स्वस्थ दिखते हैं",
  "adv.heroNoneSub": "अभी कुछ बड़ा ठीक करने को नहीं। नीचे की तारीखों पर नज़र रखें।",
  "adv.profitNow": "अभी का मुनाफ़ा, प्रति माह",
  "adv.profitAfter": "सब करने पर",
  "adv.margin": "मार्जिन",
  "adv.health": "बिज़नेस सेहत",
  "adv.h.strong": "मज़बूत",
  "adv.h.steady": "स्थिर",
  "adv.h.needs_work": "सुधार चाहिए",
  "adv.f.margin": "मुनाफ़ा मार्जिन",
  "adv.f.growth": "बिक्री वृद्धि",
  "adv.f.cost": "खर्च पर नियंत्रण",
  "adv.f.collections": "वसूली",
  "adv.f.runway": "कैश बफ़र",
  "adv.fv.margin": "बिक्री का {v}% बचता है",
  "adv.fv.growth": "पिछले 90 दिनों से {v}%",
  "adv.fv.cost": "खर्च पहले से {v}%",
  "adv.fv.collections": "उधार का {v}% देर से है",
  "adv.fv.runway": "{v} महीने के खर्च जितना कैश",
  "adv.fv.none": "डेटा कम है",
  "adv.note": "DHAN AI का नोट",
  "adv.noteAuto": "पिछले 90 दिनों में आपके बिज़नेस ने {revenue} की बिक्री पर {profit} मुनाफ़ा कमाया, यानी {margin}% मार्जिन। नीचे की बातें ठीक करने पर हर महीने लगभग {gain} जुड़ सकते हैं।",
  "adv.noteAutoNone": "पिछले 90 दिनों में आपके बिज़नेस ने {revenue} की बिक्री पर {profit} मुनाफ़ा कमाया, यानी {margin}% मार्जिन। अभी कुछ बड़ा ठीक करने को नहीं।",
  "adv.pnl": "लाभ-हानि, पिछले 6 महीने",
  "adv.revenue": "बिक्री",
  "adv.expenses": "खर्च",
  "adv.profit": "मुनाफ़ा",
  "adv.cost": "पैसा कहाँ जाता है",
  "adv.costSub": "बिक्री का हिस्सा, आपके तरह के बिज़नेस के अंदाज़ी पैमाने के मुकाबले। यह ऑडिट किया हुआ बेंचमार्क नहीं है।",
  "adv.of": "बिक्री का",
  "adv.usual": "सामान्य {n}%",
  "adv.over": "सामान्य से ज़्यादा",
  "adv.ok": "सामान्य",
  "adv.under": "सामान्य से कम",
  "adv.plan": "आपकी एक्शन योजना",
  "adv.planSub": "जो आप करेंगे उन पर टिक करें और असर देखें।",
  "adv.perMonth": "+{amount} / माह",
  "adv.protects": "आपको बचाता है",
  "adv.p.high": "पहले करें",
  "adv.p.medium": "फिर",
  "adv.p.low": "फुर्सत में",
  "adv.a.cost": "खर्च",
  "adv.a.revenue": "आमदनी",
  "adv.a.cash": "कैश",
  "adv.a.tax": "टैक्स",
  "adv.a.risk": "जोखिम",
  "adv.selected": "ये {n} करने पर: हर महीने {amount} ज़्यादा, मार्जिन {from}% से {to}%",
  "adv.selectNone": "कोई सुझाव चुनें और देखें वह क्या जोड़ता है।",
  "adv.assume": "अनुमान बताई गई मान्यताओं पर हैं: दोबारा मोलभाव से लगभग {neg}% बचत, देर वाले इनवॉइस में फंसा पैसा साल का लगभग {carry}% महंगा, और दाम बढ़ाने का {churn}% फ़ायदा बचता है।",
  "adv.breakeven": "ब्रेक-ईवन",
  "adv.beSub": "तय खर्च (वेतन, किराया, बिजली आदि) निकालने के लिए हर महीने कितनी बिक्री चाहिए।",
  "adv.beNeeded": "{amount} / माह",
  "adv.beAbove": "आप हर महीने {amount} बेचते हैं, ब्रेक-ईवन से {pct}% ऊपर।",
  "adv.beBelow": "आप हर महीने {amount} बेचते हैं, ब्रेक-ईवन से नीचे।",
  "adv.beNone": "आपका खर्च बिक्री के साथ बढ़ता है, इसलिए तय ब्रेक-ईवन नहीं दिखता।",
  "adv.calendar": "जिन तारीखों को न चूकें",
  "adv.cal.gstr1": "GSTR-1 (बिक्री रिटर्न)",
  "adv.cal.gstr3b": "GSTR-3B (GST भुगतान)",
  "adv.cal.tds": "TDS जमा",
  "adv.cal.advance_tax": "एडवांस टैक्स किस्त",
  "adv.today": "आज",
  "adv.inDays": "{n} दिन में",
  "adv.calNote": "मासिक GST फाइलर मानकर।",
  "adv.disclaimer": "यह आपके अपने आँकड़ों से मार्गदर्शन है, टैक्स या कानूनी सलाह नहीं। टैक्स की बातें अपने CA से पक्की करें।",
  "adv.ask": "DHAN AI से पूछें",
  "adv.go.collect": "इनवॉइस वसूलें",
  "adv.go.itc": "GST सहायक खोलें",
  "adv.go.runway": "कैश कैलेंडर",
  "adv.go.tax_aside": "GST सहायक खोलें",
  "adv.steps": "क्या करें",

  "adv.cost_over.title": "{category} का खर्च घटाएं",
  "adv.cost_over.why": "आपने {category} पर {amount} खर्च किए: बिक्री का {share}%, जबकि लगभग {benchmark}% सामान्य है। अंतर का आधा घटाने से हर महीने लगभग {impact} बचेंगे।",
  "adv.cost_over.s1": "पिछले 3 महीने के {category} के सारे भुगतान लिखें और जो ज़रूरी नहीं थे उन पर निशान लगाएं।",
  "adv.cost_over.s2": "{category} की मासिक सीमा तय करें और हर रविवार देखें।",
  "adv.cost_over.s3": "अगला भुगतान करने से पहले सबसे बड़ी चीज़ों के दो नए भाव लें।",
  "adv.vendor_creep.title": "{vendor} महंगा होता जा रहा है",
  "adv.vendor_creep.why": "{vendor} को आपका औसत भुगतान पिछले 45 दिनों में {old} से {new} (+{pct}%) हो गया।",
  "adv.vendor_creep.s1": "{vendor} से कारण पूछें और पुराना भाव लिखित में मांगें।",
  "adv.vendor_creep.s2": "एक और सप्लायर से भाव लें और {vendor} को बता दें।",
  "adv.vendor_creep.s3": "थोक में या तय मासिक भाव पर लें, अगर इससे दर टिकती है।",
  "adv.vendor_dependence.title": "आपके {category} का {share}% {vendor} को जाता है",
  "adv.vendor_dependence.why": "आपने 90 दिनों में {vendor} को {amount} दिए। एक ही सप्लायर पर निर्भरता जोखिम है और मोलभाव कमज़ोर करती है।",
  "adv.vendor_dependence.s1": "{vendor} से वॉल्यूम डिस्काउंट मांगें। 3% भी जुड़ता है।",
  "adv.vendor_dependence.s2": "इन्हीं चीज़ों के लिए दूसरा सप्लायर तैयार करें।",
  "adv.vendor_dependence.s3": "जल्दी भुगतान तभी करें जब इसके बदले छूट मिले।",
  "adv.customer_concentration.title": "{name} आपकी आमदनी का {share}% है",
  "adv.customer_concentration.why": "अगर {name} देर से चुकाए या चला जाए, तो आपके कैश को बड़ा झटका लगेगा।",
  "adv.customer_concentration.s1": "{name} के साथ भुगतान की शर्तें और एडवांस तय करें।",
  "adv.customer_concentration.s2": "इस तिमाही में इसी आकार के दो और ग्राहक जोड़ने का लक्ष्य रखें।",
  "adv.customer_concentration.s3": "उनके एक महीने के भुगतान जितना कैश बफ़र रखें।",
  "adv.collect.title": "बकाया {amount} वसूलें",
  "adv.collect.why": "{count} इनवॉइस देर से हैं; सबसे पुराना {party} का {days} दिन का है। वहाँ फंसा पैसा हर महीने लगभग {impact} का ब्याज (साल का 18% मानकर) खाता है और कैश घटाता है।",
  "adv.collect.s1": "आज ही हर देर वाले ग्राहक को पेमेंट लिंक भेजें। DHAN एक टैप में कर देता है।",
  "adv.collect.s2": "इस हफ़्ते भुगतान पर छोटी छूट दें और नए इनवॉइस में लेट फ़ीस जोड़ें।",
  "adv.collect.s3": "जो पूरा नहीं दे सकते उनसे अभी आंशिक भुगतान मांगें।",
  "adv.price_rise.title": "दाम 3% बढ़ाएं",
  "adv.price_rise.why": "आपका मार्जिन {margin}% है, जो कम है। 3% बढ़ोतरी से कुछ ग्राहक जाने पर भी हर महीने लगभग {gain} जुड़ते हैं।",
  "adv.price_rise.s1": "पहले नए ग्राहकों और नए ऑर्डर पर दाम बढ़ाएं।",
  "adv.price_rise.s2": "पुराने ग्राहकों को एक हफ़्ता पहले कारण के साथ बताएं।",
  "adv.price_rise.s3": "आगे बढ़ने से पहले एक महीना दोबारा ऑर्डर देखें।",
  "adv.subscriptions.title": "{count} बार-बार लगने वाले चार्ज जांचें",
  "adv.subscriptions.why": "तय मासिक चार्ज ({names} जैसे) मिलकर लगभग {monthly} प्रति माह हैं। ज़्यादातर बिज़नेस इनका दसवां हिस्सा हटा या घटा सकते हैं।",
  "adv.subscriptions.s1": "हर एक का काम और उसे कौन इस्तेमाल करता है, लिखें।",
  "adv.subscriptions.s2": "जो इस्तेमाल में नहीं उसे बंद करें। बाकी को सस्ते या सालाना प्लान पर ले जाएं।",
  "adv.subscriptions.s3": "हर तिमाही इनकी समीक्षा का रिमाइंडर लगाएं।",
  "adv.marketing_roi.title": "मार्केटिंग बिक्री से तेज़ बढ़ रही है",
  "adv.marketing_roi.why": "मार्केटिंग खर्च {marketing_growth}% बढ़ा जबकि बिक्री {revenue_growth}%। अब यह बिक्री का {share}% है।",
  "adv.marketing_roi.s1": "देखें कि कौन सा चैनल पैसे देने वाले ग्राहक लाता है, सिर्फ़ क्लिक नहीं।",
  "adv.marketing_roi.s2": "सबसे कमज़ोर चैनल दो हफ़्ते रोकें और बिक्री देखें।",
  "adv.marketing_roi.s3": "बजट काम करने वाली जगह लगाएं। पांचवां हिस्सा घटाने से हर महीने लगभग {impact} बचते हैं।",
  "adv.itc.title": "{amount} का इनपुट टैक्स क्रेडिट लें",
  "adv.itc.why": "{suppliers} सप्लायर्स के बिलों पर GSTIN नहीं है, इसलिए आपके चुकाए GST में से लगभग {amount} क्लेम नहीं हो सकता।",
  "adv.itc.s1": "हर सप्लायर से उनके GSTIN वाला GST इनवॉइस मांगें।",
  "adv.itc.s2": "बिल दर्ज करते समय DHAN में GSTIN जोड़ें।",
  "adv.itc.s3": "GST सहायक का CA पैक अपने अकाउंटेंट को दें।",
  "adv.spike.title": "{category} का खर्च अचानक बढ़ा",
  "adv.spike.why": "{category} पर पिछले 30 दिनों में {last30} लगे, पहले लगभग {usual} प्रति माह था।",
  "adv.spike.s1": "{category} के सबसे बड़े भुगतानों में गलती या एकमुश्त खर्च जांचें।",
  "adv.spike.s2": "अगर यह नई आदत है तो मासिक सीमा तय करें।",
  "adv.runway.title": "कैश बफ़र बनाएं",
  "adv.runway.why": "आपके पास {cash} है, यानी लगभग {months} महीने का खर्च। 2 महीने से कम हो तो एक धीमा महीना भारी पड़ सकता है।",
  "adv.runway.s1": "पहले देर वाले इनवॉइस वसूलें।",
  "adv.runway.s2": "गैर-ज़रूरी बिल एक हफ़्ता आगे करें। DHAN AI यह योजना बना सकता है।",
  "adv.runway.s3": "बैंक में तीन महीने का खर्च रखने का लक्ष्य रखें।",
  "adv.tax_aside.title": "टैक्स के लिए पैसा अलग रखें",
  "adv.tax_aside.why": "पिछले 90 दिनों में आपने {profit} कमाए। लगभग {set_aside} अलग रखने से झटका नहीं लगेगा। अगली एडवांस-टैक्स तारीख {date} है ({days} दिन में)।",
  "adv.tax_aside.s1": "आज ही यह रकम अलग खाते में डालें।",
  "adv.tax_aside.s2": "अपने CA से इस साल का एडवांस टैक्स अनुमान लगवाएं।",

  "ev.msg": "{who}: {text}",
  "ev.who.owner": "आप",
  "ev.who.customer": "ग्राहक",
  "ev.pay_failed": "ग्राहक का {amount} का भुगतान विफल: {reason}",
  "ev.dispute": "ग्राहक ने विवाद उठाया: {reason}",
  "ev.dispute_resolved": "विवाद सुलझा",
  "notif.pay_failed": "{party} का भुगतान विफल हुआ",
  "notif.pay_failedBody": "{amount} · {reason}",
  "notif.msg": "{party} ने आपको संदेश भेजा",
  "notif.dispute": "{party} ने इनवॉइस पर विवाद उठाया",
  "ud.reply": "ग्राहक को संदेश भेजें",
  "ud.replyPlaceholder": "जवाब लिखें। ग्राहक इसे अपने DHAN पोर्टल में पढ़ेगा।",
  "ud.replySend": "भेजें",
  "ud.resolve": "उनका विवाद सुलझा हुआ मानें",
  "ud.disputedChip": "विवाद में",
  "ud.failedChip": "भुगतान विफल: {reason}",
  "ud.chat": "बातचीत",

  "cu.hello": "नमस्ते, {name}",
  "cu.owe": "आपको चुकाना है",
  "cu.across": "{n} इनवॉइस में",
  "cu.across1": "1 इनवॉइस में",
  "cu.overdue": "{amount} देर से है",
  "cu.onTime": "कुछ देर से नहीं",
  "cu.allClear": "अभी आपका कुछ बाकी नहीं है",
  "cu.allClearBody": "जब कोई दुकान आपको अपने उधार में जोड़ेगी, वह यहाँ भुगतान के तरीके के साथ दिखेगी।",
  "cu.failedBanner": "एक भुगतान पूरा नहीं हुआ",
  "cu.failedBannerBody": "कोई पैसा नहीं कटा। नीचे के इनवॉइस से दोबारा कोशिश करें।",
  "cu.shops": "आपकी दुकानें",
  "cu.due": "देय {date}",
  "cu.late": "{n} दिन देर",
  "cu.pay": "अभी चुकाएं",
  "cu.view": "विवरण",
  "cu.paidChip": "चुकाया",
  "cu.promised": "आपने {date} का वादा किया",
  "cu.under": "जांच में",
  "cu.failedChip": "भुगतान विफल",
  "cu.settled": "हाल में चुकाए",
  "cu.activity": "दुकानों से अपडेट",
  "cu.activityNone": "अभी कोई अपडेट नहीं।",
  "cu.act.sent": "{shop} ने आपको रिमाइंडर भेजा",
  "cu.act.msg": "{shop}: {text}",
  "cu.act.payment": "{shop} को आपका {amount} का भुगतान मिला",
  "cu.act.claim_confirmed": "{shop} ने आपका {amount} का भुगतान पक्का किया",
  "cu.act.claim_rejected": "{shop} को आपका भुगतान नहीं मिला",
  "cu.act.dispute_resolved": "{shop} ने आपका विवाद सुलझाया",
  "cu.back": "वापस",
  "cu.amountDue": "देय रकम",
  "cu.ofTotal": "{total} में से",
  "cu.lateFee": "अब तक लेट फ़ीस: {amount}",
  "cu.paidFull": "यह इनवॉइस पूरा चुकाया जा चुका है। धन्यवाद।",
  "cu.failedTitle": "आपका पिछला भुगतान विफल रहा ({reason})",
  "cu.failedBody": "कोई पैसा नहीं कटा और {shop} को बता दिया गया है। आप फिर कोशिश करें या बताएं कब चुकाएंगे।",
  "cu.retry": "फिर कोशिश करें",
  "cu.promiseTitle": "और समय चाहिए?",
  "cu.promiseBody": "तारीख का वादा करें। {shop} को बताया जाएगा और तब तक रिमाइंडर रुकेंगे।",
  "cu.promiseBtn": "यह तारीख पक्की करें",
  "cu.promiseDone": "वादा दर्ज। {shop} को बता दिया गया है।",
  "cu.messages": "{shop} से बातचीत",
  "cu.msgPlaceholder": "दुकान को लिखें…",
  "cu.send": "भेजें",
  "cu.you": "आप",
  "cu.noMessages": "अभी कोई संदेश नहीं। इस इनवॉइस के बारे में दुकान से कुछ भी पूछें।",
  "cu.dispute": "यह सही नहीं है",
  "cu.disputeTitle": "क्या गलत है?",
  "cu.disputeSend": "दुकान को बताएं",
  "cu.disputeNote": "दुकान को बताया जाएगा और उनके जवाब तक अपने-आप रिमाइंडर रुकेंगे।",
  "cu.disputeOpen": "आपने विवाद उठाया है। {shop} यहीं जवाब देगी।",
  "cu.dr.wrong_amount": "रकम गलत है",
  "cu.dr.not_received": "मुझे यह सेवा या माल नहीं मिला",
  "cu.dr.already_paid": "मैं पहले ही चुका चुका हूं",
  "cu.dr.other": "कुछ और",
  "cu.history": "इतिहास",
  "cu.ev.created": "इनवॉइस बना",
  "cu.ev.sent": "आपको रिमाइंडर भेजा गया",
  "cu.ev.payment": "आपने {amount} चुकाए",
  "cu.ev.pay_failed": "भुगतान विफल: {reason}",
  "cu.ev.promise": "आपने {date} का वादा किया",
  "cu.ev.dispute": "आपने विवाद उठाया",
  "cu.ev.dispute_resolved": "विवाद सुलझा",
  "cu.ev.settled": "पूरा चुकाया",
  "cu.ev.claim": "आपने कहा कि {amount} चुकाए",
  "cu.ev.claim_confirmed": "दुकान ने आपका भुगतान पक्का किया",
  "cu.ev.claim_rejected": "दुकान को आपका भुगतान नहीं मिला",
  "cu.ev.msg.owner": "{shop}: {text}",
  "cu.ev.msg.customer": "आप: {text}",
  "cu.reason.insufficient_funds": "बैलेंस पर्याप्त नहीं",
  "cu.reason.bank_down": "बैंक जवाब नहीं दे रहा",
  "cu.reason.declined": "कार्ड अस्वीकृत",
  "cu.reason.cancelled": "रद्द किया",
  "cu.pm.title": "{shop} को चुकाएं",
  "cu.pm.amount": "रकम",
  "cu.pm.full": "पूरी रकम",
  "cu.pm.part": "आंशिक भुगतान",
  "cu.pm.method": "किससे चुकाएं",
  "cu.pm.upi": "UPI",
  "cu.pm.card": "कार्ड",
  "cu.pm.netbanking": "नेट बैंकिंग",
  "cu.pm.sandbox": "प्रैक्टिस भुगतान: कोई असली पैसा नहीं हिलता। चुनें कि क्या हो, और देखें DHAN उसे कैसे संभालता है।",
  "cu.pm.outcome": "प्रैक्टिस नतीजा",
  "cu.pm.o.success": "भुगतान सफल हो",
  "cu.pm.o.insufficient_funds": "बैलेंस पर्याप्त नहीं",
  "cu.pm.o.bank_down": "बैंक जवाब नहीं दे रहा",
  "cu.pm.o.declined": "कार्ड अस्वीकृत",
  "cu.pm.o.cancelled": "मैं रद्द करता हूं",
  "cu.pm.go": "{amount} चुकाएं",
  "cu.pm.processing": "प्रोसेस हो रहा है…",
  "cu.pm.successTitle": "भुगतान मिल गया",
  "cu.pm.receipt": "रसीद {id}",
  "cu.pm.left": "इस इनवॉइस पर अभी {amount} बाकी है।",
  "cu.pm.settled": "यह इनवॉइस पूरा चुकाया गया।",
  "cu.pm.failTitle": "भुगतान पूरा नहीं हुआ",
  "cu.pm.failBody": "कारण: {reason}। कोई पैसा नहीं कटा। {shop} को बता दिया गया है।",
  "cu.pm.other": "दूसरा तरीका चुनें",
  "cu.pm.later": "बजाय इसके तारीख का वादा करें",
  "cu.pm.done": "ठीक है",
  "cu.reg.title": "जो चुकाना है, एक ही जगह",
  "cu.reg.sub": "देखें किन दुकानों ने आपको उधार पर लिखा है। चुकाएं, तारीख का वादा करें या उन्हें संदेश भेजें।",
  "cu.reg.name": "आपका नाम",
  "cu.reg.why": "हम आपका नंबर वेरिफाई करते हैं ताकि सिर्फ़ आप अपना बकाया देख सकें।",
  "cu.reg.sendCode": "कोड भेजें",
  "cu.reg.create": "अकाउंट बनाएं",
  "cu.reg.haveAcc": "पहले से रजिस्टर्ड हैं?",
  "cu.reg.codeSub": "{phone} पर भेजा 6 अंकों का कोड डालें।",
  "cu.reg.heading": "ग्राहक अकाउंट",
  "cu.reg.password": "पासवर्ड चुनें",
  "auth.customerLink": "ग्राहक हैं? देखें आपको क्या चुकाना है",
  "auth.ownerLink": "बिज़नेस चलाते हैं? बिज़नेस अकाउंट बनाएं",
};
