// Copy for the Udhaar system: owner screens, notifications, timeline, customer pay page.

export const enUd = {
  // page + cards
  "ud.claimsBanner": "{n} customers say they've paid. Confirm once the money arrives.",
  "ud.claimsBannerOne": "{n} customer says they've paid. Confirm once the money arrives.",
  "ud.overLimit": "Over limit",
  "ud.noLimit": "Needs payment history",
  "ud.simBanner": "WhatsApp and email run in simulation mode. Messages appear on a simulated customer phone. Add keys in .env to send for real.",
  "ud.tabCustomers": "Customers",
  "ud.notSent": "Not sent yet",
  "ud.sentNotOpened": "Sent, not opened",
  "ud.seen": "Seen {when}",
  "ud.promised": "Promised {date}",
  "ud.saysPaid": "Says paid {amount}",
  "ud.received": "{paid} of {total} received",
  "ud.lateFee": "+{amount} late fee",
  "ud.sendLink": "Send payment link",
  "ud.sendReminder": "Send reminder",
  "ud.recordPayment": "Record payment",
  "ud.confirmReceived": "Confirm received",
  "ud.notReceived": "Not received",
  "ud.timeline": "Timeline",
  "ud.customerPhone": "Customer's phone",
  "ud.copyLink": "Copy link",
  "ud.openLink": "Open customer view",
  "ud.linkCopied": "Link copied",
  "ud.claimConfirmed": "Payment confirmed and recorded",
  "ud.claimRejected": "Marked as not received",
  "ud.paymentRecorded": "Payment recorded",
  "ud.settled": "Settled",
  "ud.autoRemind": "Auto-reminders",
  "ud.autoRemindOn": "On. DHAN nudges them automatically",
  "ud.autoRemindOff": "Off",
  "ud.ladder": "Reminder schedule",
  "ud.ladderNote": "One message per step, tone getting firmer. Paused while a promise is pending or a payment claim awaits you.",
  "ud.noEvents": "Nothing has happened yet.",

  // steps
  "step.first": "First request",
  "step.pre": "Friendly heads-up",
  "step.due": "Due today",
  "step.late3": "Gentle nudge",
  "step.late7": "Firm reminder",
  "step.final": "Final notice",

  // add entry
  "ud.addTitle": "New udhaar entry",
  "ud.email": "Email (optional)",
  "ud.customerLang": "Customer's language",
  "ud.dueIn": "Due in",
  "ud.days": "{n} days",
  "ud.lateFeeLabel": "Late fee",
  "ud.lateFeeNone": "None",
  "ud.lateFeePct": "{n}% per month",
  "ud.autoRemindLabel": "Send reminders automatically",
  "ud.aboveLimit": "This is above the suggested limit of {limit} for {party}.",
  "ud.riskyCustomer": "{party} usually pays late (score {score}). Consider a smaller amount or a shorter due date.",
  "ud.savedSend": "Entry added. Send the payment link now?",

  // send modal
  "ud.sendTitle": "Send to {party}",
  "ud.channelEmail": "Email",
  "ud.channelWhatsApp": "WhatsApp",
  "ud.simulated": "Simulated",
  "ud.live": "Live",
  "ud.addEmail": "Add an email address",
  "ud.addPhone": "Add a WhatsApp number",
  "ud.message": "Message",
  "ud.language": "Language",
  "ud.send": "Send now",
  "ud.sending": "Sending…",
  "ud.sentTo": "Sent",
  "ud.sentSim": "Simulated, shown on the customer's phone",
  "ud.sentFail": "Failed",
  "ud.done": "Done",
  "ud.viewPhone": "See it on the customer's phone",
  "ud.pickChannel": "Pick at least one channel with a contact.",
  "ud.sendFail": "Couldn't send. Please try again.",

  // demo phone
  "ph.title": "Customer's phone (simulation)",
  "ph.whatsapp": "WhatsApp",
  "ph.email": "Email",
  "ph.empty": "Nothing sent yet.",
  "ph.openLink": "Open the pay link as the customer",
  "ph.note": "This is a simulation. With WhatsApp / SMTP keys in .env the same message goes to the real number and inbox.",
  "ph.to": "To {to}",
  "ph.typing": "online",

  // payment modal
  "ud.payTitle": "Record a payment from {party}",
  "ud.payAmount": "Amount received",
  "ud.payMode": "How was it paid?",
  "ud.payFull": "Full {amount}",
  "ud.payHalf": "Half",
  "ud.paySave": "Record payment",
  "ud.outstanding": "Outstanding {amount}",

  // customers
  "ud.custTitle": "Customers and their track record",
  "ud.custSub": "A transparent score from how each customer has actually paid you.",
  "ud.custEmpty": "No customers yet.",
  "ud.custEmptyBody": "Add an entry and DHAN starts learning who pays on time.",
  "ud.label.reliable": "Reliable",
  "ud.label.late": "Usually late",
  "ud.label.risky": "High risk",
  "ud.score": "Score {n}",
  "ud.avgLate": "Pays {n} days late on average",
  "ud.onTimeRate": "{n}% paid on time",
  "ud.noHistory": "No payment history yet",
  "ud.suggestedLimit": "Suggested limit",
  "ud.suggestedLimitHint": "The most udhaar we'd suggest giving them now",
  "ud.openInvoices": "Open now",
  "ud.history": "Payment history",
  "ud.daysLate": "{n} days late",
  "ud.onTime": "On time",
  "ud.howScored": "How the score works",
  "ud.howScoredBody": "Starts at 100. Loses up to 55 points for habitually paying late, and up to 30 for invoices overdue right now. The limit is 1.5× the largest invoice they've paid, scaled by the score, minus what they already owe.",
  "ud.newForCustomer": "New entry for this customer",
  "ud.invoices": "{n} invoices",

  // timeline events
  "ev.created": "Entry created",
  "ev.sent": "Sent via {channel}",
  "ev.sentSim": "Sent via {channel} (simulated)",
  "ev.viewed": "Customer opened the link",
  "ev.promise": "Promised to pay on {date}",
  "ev.note": "Customer wrote: “{text}”",
  "ev.claim": "Customer says they paid {amount}",
  "ev.claim_confirmed": "You confirmed the payment of {amount}",
  "ev.claim_rejected": "You marked the claim of {amount} as not received",
  "ev.payment": "Payment of {amount} recorded ({mode})",
  "ev.settled": "Fully settled",
  "ev.auto_reminder": "Auto-reminder sent: {step}",

  // notifications
  "notif.title": "Notifications",
  "notif.empty": "No notifications yet.",
  "notif.emptyBody": "You'll see it here the moment a customer opens a link, promises a date or says they've paid.",
  "notif.viewed": "{party} opened your payment link",
  "notif.viewedBody": "{amount} outstanding",
  "notif.promise": "{party} promised to pay on {date}",
  "notif.promiseBody": "Auto-reminders are paused until then",
  "notif.claim": "{party} says they paid {amount}",
  "notif.claimBody": "Confirm once the money reaches your account",
  "notif.note": "{party} sent you a message",
  "notif.payment_auto": "{amount} received from {party}",
  "notif.payment_autoBody": "Paid online and recorded automatically",
  "notif.live": "Live",

  // settings
  "set.collect": "Collect payments",
  "set.collectBody": "Your UPI ID powers the QR code and the Pay button on every customer's payment page.",
  "set.upi": "UPI ID",
  "set.upiHint": "e.g. gowurk@okhdfcbank",
  "set.upiSave": "Save UPI ID",
  "set.upiSaved": "UPI ID saved",
  "set.upiInvalid": "That doesn't look like a UPI ID (name@bank).",
  "set.integrations": "Connected services",
  "set.int.email": "Email",
  "set.int.whatsapp": "WhatsApp",
  "set.int.razorpay": "Razorpay online payments",
  "set.int.live": "Live",
  "set.int.simulated": "Simulation mode",
  "set.int.off": "Not connected",
  "set.int.hint": "Add the keys to backend/.env and restart. No other changes needed.",

  // customer pay page
  "pay.secure": "Secure payment request",
  "pay.hello": "Hi {party}",
  "pay.requests": "{business} is requesting",
  "pay.forNote": "For: {note}",
  "pay.due": "Due {date}",
  "pay.dueIn": "Due in {n} days",
  "pay.dueToday": "Due today",
  "pay.overdue": "{n} days overdue",
  "pay.lateFee": "A late fee of {amount} has built up so far.",
  "pay.partial": "{paid} already paid · {left} left",
  "pay.paidTitle": "All settled. Thank you!",
  "pay.paidBody": "{business} has received the full amount.",
  "pay.howToPay": "Pay with UPI",
  "pay.scan": "Scan with any UPI app (GPay, PhonePe, Paytm…)",
  "pay.payApp": "Pay with UPI app",
  "pay.copyUpi": "Copy UPI ID",
  "pay.upiCopied": "UPI ID copied",
  "pay.online": "Pay online (cards, netbanking, wallets)",
  "pay.noMethod": "Ask {business} how to pay, then tell them below once you have.",
  "pay.alreadyPaid": "Already paid?",
  "pay.alreadyPaidBody": "Let {business} know so they can confirm it.",
  "pay.ref": "UPI / reference number (optional)",
  "pay.iPaid": "I've paid",
  "pay.claimSent": "Thanks. {business} has been told and will confirm shortly.",
  "pay.claimPending": "You told {business} you paid {amount}. They'll confirm shortly.",
  "pay.needTime": "Need more time?",
  "pay.needTimeBody": "Pick the day you'll pay. {business} will see it.",
  "pay.promiseBtn": "I'll pay on this date",
  "pay.promiseSent": "Noted. {business} knows you'll pay on {date}.",
  "pay.promiseCurrent": "You promised to pay on {date}.",
  "pay.message": "Message {business}",
  "pay.messageHint": "e.g. Please resend the GST invoice",
  "pay.sendMessage": "Send message",
  "pay.messageSent": "Message sent.",
  "pay.invalid": "This payment link isn't valid",
  "pay.invalidBody": "Check the link you received, or ask the business to send it again.",
  "pay.poweredBy": "Powered by DHAN",
  "pay.error": "Something went wrong. Please try again.",
};

export const hiUd = {
  "ud.claimsBanner": "{n} ग्राहक कहते हैं कि भुगतान कर दिया है। पैसा आने पर पुष्टि करें।",
  "ud.claimsBannerOne": "{n} ग्राहक कहते हैं कि भुगतान कर दिया है। पैसा आने पर पुष्टि करें।",
  "ud.overLimit": "सीमा से ऊपर",
  "ud.noLimit": "भुगतान इतिहास चाहिए",
  "ud.simBanner": "WhatsApp और ईमेल सिमुलेशन मोड में हैं। संदेश नकली ग्राहक फ़ोन पर दिखते हैं। असली भेजने के लिए .env में कुंजियां डालें।",
  "ud.tabCustomers": "ग्राहक",
  "ud.notSent": "अभी भेजा नहीं",
  "ud.sentNotOpened": "भेजा, खुला नहीं",
  "ud.seen": "देखा {when}",
  "ud.promised": "वादा {date}",
  "ud.saysPaid": "कहते हैं {amount} चुका दिया",
  "ud.received": "{total} में से {paid} मिले",
  "ud.lateFee": "+{amount} विलंब शुल्क",
  "ud.sendLink": "भुगतान लिंक भेजें",
  "ud.sendReminder": "याद दिलाएं",
  "ud.recordPayment": "भुगतान दर्ज करें",
  "ud.confirmReceived": "मिल गया, पक्का करें",
  "ud.notReceived": "नहीं मिला",
  "ud.timeline": "घटनाक्रम",
  "ud.customerPhone": "ग्राहक का फ़ोन",
  "ud.copyLink": "लिंक कॉपी करें",
  "ud.openLink": "ग्राहक का पेज खोलें",
  "ud.linkCopied": "लिंक कॉपी हो गया",
  "ud.claimConfirmed": "भुगतान की पुष्टि हुई और दर्ज हो गया",
  "ud.claimRejected": "नहीं मिला के रूप में दर्ज",
  "ud.paymentRecorded": "भुगतान दर्ज हो गया",
  "ud.settled": "निपट गया",
  "ud.autoRemind": "अपने-आप याद दिलाना",
  "ud.autoRemindOn": "चालू। DHAN खुद याद दिलाता है",
  "ud.autoRemindOff": "बंद",
  "ud.ladder": "याद दिलाने का कार्यक्रम",
  "ud.ladderNote": "हर चरण पर एक संदेश, लहजा धीरे-धीरे सख़्त। वादे या भुगतान के दावे के दौरान रुका रहता है।",
  "ud.noEvents": "अभी कुछ नहीं हुआ।",

  "step.first": "पहला अनुरोध",
  "step.pre": "दोस्ताना याद",
  "step.due": "आज देय",
  "step.late3": "हल्की याद",
  "step.late7": "सख़्त याद",
  "step.final": "अंतिम सूचना",

  "ud.addTitle": "नई उधार एंट्री",
  "ud.email": "ईमेल (वैकल्पिक)",
  "ud.customerLang": "ग्राहक की भाषा",
  "ud.dueIn": "देय अवधि",
  "ud.days": "{n} दिन",
  "ud.lateFeeLabel": "विलंब शुल्क",
  "ud.lateFeeNone": "कोई नहीं",
  "ud.lateFeePct": "{n}% प्रति माह",
  "ud.autoRemindLabel": "अपने-आप याद दिलाएं",
  "ud.aboveLimit": "यह {party} के लिए सुझाई सीमा {limit} से ऊपर है।",
  "ud.riskyCustomer": "{party} आमतौर पर देर से चुकाते हैं (स्कोर {score})। छोटी राशि या कम अवधि पर विचार करें।",
  "ud.savedSend": "एंट्री जुड़ गई। अभी भुगतान लिंक भेजें?",

  "ud.sendTitle": "{party} को भेजें",
  "ud.channelEmail": "ईमेल",
  "ud.channelWhatsApp": "WhatsApp",
  "ud.simulated": "सिमुलेशन",
  "ud.live": "लाइव",
  "ud.addEmail": "ईमेल पता जोड़ें",
  "ud.addPhone": "WhatsApp नंबर जोड़ें",
  "ud.message": "संदेश",
  "ud.language": "भाषा",
  "ud.send": "अभी भेजें",
  "ud.sending": "भेजा जा रहा है…",
  "ud.sentTo": "भेजा गया",
  "ud.sentSim": "सिमुलेशन, ग्राहक के फ़ोन पर दिखेगा",
  "ud.sentFail": "विफल",
  "ud.done": "हो गया",
  "ud.viewPhone": "ग्राहक के फ़ोन पर देखें",
  "ud.pickChannel": "कम से कम एक माध्यम चुनें जिसका संपर्क हो।",
  "ud.sendFail": "भेज नहीं सके। फिर कोशिश करें।",

  "ph.title": "ग्राहक का फ़ोन (सिमुलेशन)",
  "ph.whatsapp": "WhatsApp",
  "ph.email": "ईमेल",
  "ph.empty": "अभी कुछ भेजा नहीं गया।",
  "ph.openLink": "ग्राहक की तरह पे-लिंक खोलें",
  "ph.note": "यह सिमुलेशन है। .env में WhatsApp / SMTP कुंजियां डालने पर यही संदेश असली नंबर और इनबॉक्स पर जाएगा।",
  "ph.to": "{to} को",
  "ph.typing": "ऑनलाइन",

  "ud.payTitle": "{party} से भुगतान दर्ज करें",
  "ud.payAmount": "मिली राशि",
  "ud.payMode": "भुगतान कैसे हुआ?",
  "ud.payFull": "पूरा {amount}",
  "ud.payHalf": "आधा",
  "ud.paySave": "भुगतान दर्ज करें",
  "ud.outstanding": "बाकी {amount}",

  "ud.custTitle": "ग्राहक और उनका रिकॉर्ड",
  "ud.custSub": "हर ग्राहक ने आपको असल में कैसे चुकाया, उसके आधार पर पारदर्शी स्कोर।",
  "ud.custEmpty": "अभी कोई ग्राहक नहीं।",
  "ud.custEmptyBody": "एंट्री जोड़ें, DHAN सीखेगा कि कौन समय पर चुकाता है।",
  "ud.label.reliable": "भरोसेमंद",
  "ud.label.late": "अक्सर देर",
  "ud.label.risky": "ज़्यादा जोखिम",
  "ud.score": "स्कोर {n}",
  "ud.avgLate": "औसतन {n} दिन देर से चुकाते हैं",
  "ud.onTimeRate": "{n}% समय पर चुकाया",
  "ud.noHistory": "अभी भुगतान इतिहास नहीं",
  "ud.suggestedLimit": "सुझाई सीमा",
  "ud.suggestedLimitHint": "अभी इन्हें अधिकतम इतना उधार देना ठीक रहेगा",
  "ud.openInvoices": "अभी खुले",
  "ud.history": "भुगतान इतिहास",
  "ud.daysLate": "{n} दिन देर",
  "ud.onTime": "समय पर",
  "ud.howScored": "स्कोर कैसे बनता है",
  "ud.howScoredBody": "100 से शुरू। आदतन देर से चुकाने पर 55 तक अंक कटते हैं, और अभी बकाया इनवॉइस पर 30 तक। सीमा = उनके चुकाए सबसे बड़े इनवॉइस का 1.5 गुना, स्कोर से घटाकर, माइनस जो वे अभी देते हैं।",
  "ud.newForCustomer": "इस ग्राहक के लिए नई एंट्री",
  "ud.invoices": "{n} इनवॉइस",

  "ev.created": "एंट्री बनी",
  "ev.sent": "{channel} से भेजा",
  "ev.sentSim": "{channel} से भेजा (सिमुलेशन)",
  "ev.viewed": "ग्राहक ने लिंक खोला",
  "ev.promise": "{date} को चुकाने का वादा",
  "ev.note": "ग्राहक ने लिखा: “{text}”",
  "ev.claim": "ग्राहक का कहना है {amount} चुका दिया",
  "ev.claim_confirmed": "आपने {amount} के भुगतान की पुष्टि की",
  "ev.claim_rejected": "आपने {amount} के दावे को नहीं मिला दर्ज किया",
  "ev.payment": "{amount} का भुगतान दर्ज ({mode})",
  "ev.settled": "पूरा निपटा",
  "ev.auto_reminder": "अपने-आप याद भेजी गई: {step}",

  "notif.title": "सूचनाएं",
  "notif.empty": "अभी कोई सूचना नहीं।",
  "notif.emptyBody": "जैसे ही कोई ग्राहक लिंक खोले, तारीख बताए या भुगतान का दावा करे, यहां दिखेगा।",
  "notif.viewed": "{party} ने आपका भुगतान लिंक खोला",
  "notif.viewedBody": "{amount} बाकी",
  "notif.promise": "{party} ने {date} को चुकाने का वादा किया",
  "notif.promiseBody": "तब तक अपने-आप याद रुकी रहेगी",
  "notif.claim": "{party} कहते हैं {amount} चुका दिया",
  "notif.claimBody": "पैसा खाते में आने पर पुष्टि करें",
  "notif.note": "{party} ने आपको संदेश भेजा",
  "notif.payment_auto": "{party} से {amount} मिले",
  "notif.payment_autoBody": "ऑनलाइन चुकाया, अपने-आप दर्ज हुआ",
  "notif.live": "लाइव",

  "set.collect": "भुगतान प्राप्त करें",
  "set.collectBody": "आपकी UPI ID हर ग्राहक के भुगतान पेज पर QR कोड और Pay बटन चलाती है।",
  "set.upi": "UPI ID",
  "set.upiHint": "जैसे gowurk@okhdfcbank",
  "set.upiSave": "UPI ID सहेजें",
  "set.upiSaved": "UPI ID सहेजी गई",
  "set.upiInvalid": "यह UPI ID जैसी नहीं लगती (नाम@बैंक)।",
  "set.integrations": "जुड़ी सेवाएं",
  "set.int.email": "ईमेल",
  "set.int.whatsapp": "WhatsApp",
  "set.int.razorpay": "Razorpay ऑनलाइन भुगतान",
  "set.int.live": "लाइव",
  "set.int.simulated": "सिमुलेशन मोड",
  "set.int.off": "जुड़ा नहीं",
  "set.int.hint": "कुंजियां backend/.env में डालें और रीस्टार्ट करें। और कोई बदलाव नहीं चाहिए।",

  "pay.secure": "सुरक्षित भुगतान अनुरोध",
  "pay.hello": "नमस्ते {party}",
  "pay.requests": "{business} की ओर से अनुरोध",
  "pay.forNote": "विवरण: {note}",
  "pay.due": "देय {date}",
  "pay.dueIn": "{n} दिन में देय",
  "pay.dueToday": "आज देय",
  "pay.overdue": "{n} दिन से बाकी",
  "pay.lateFee": "अब तक {amount} का विलंब शुल्क जमा हुआ है।",
  "pay.partial": "{paid} चुकाए जा चुके · {left} बाकी",
  "pay.paidTitle": "सब निपट गया। धन्यवाद!",
  "pay.paidBody": "{business} को पूरी राशि मिल गई है।",
  "pay.howToPay": "UPI से भुगतान करें",
  "pay.scan": "किसी भी UPI ऐप (GPay, PhonePe, Paytm…) से स्कैन करें",
  "pay.payApp": "UPI ऐप से भुगतान करें",
  "pay.copyUpi": "UPI ID कॉपी करें",
  "pay.upiCopied": "UPI ID कॉपी हो गई",
  "pay.online": "ऑनलाइन भुगतान (कार्ड, नेटबैंकिंग, वॉलेट)",
  "pay.noMethod": "{business} से भुगतान का तरीका पूछें, फिर चुकाने के बाद नीचे बताएं।",
  "pay.alreadyPaid": "पहले ही चुका दिया?",
  "pay.alreadyPaidBody": "{business} को बताएं ताकि वे पुष्टि कर सकें।",
  "pay.ref": "UPI / संदर्भ नंबर (वैकल्पिक)",
  "pay.iPaid": "मैंने चुका दिया",
  "pay.claimSent": "धन्यवाद। {business} को बता दिया गया है, वे जल्द पुष्टि करेंगे।",
  "pay.claimPending": "आपने {business} को बताया कि {amount} चुका दिए। वे जल्द पुष्टि करेंगे।",
  "pay.needTime": "और समय चाहिए?",
  "pay.needTimeBody": "वह दिन चुनें जब चुकाएंगे। {business} को दिखेगा।",
  "pay.promiseBtn": "मैं इस तारीख को चुकाऊंगा",
  "pay.promiseSent": "दर्ज हुआ। {business} को पता है कि आप {date} को चुकाएंगे।",
  "pay.promiseCurrent": "आपने {date} को चुकाने का वादा किया है।",
  "pay.message": "{business} को संदेश",
  "pay.messageHint": "जैसे: कृपया GST इनवॉइस फिर भेजें",
  "pay.sendMessage": "संदेश भेजें",
  "pay.messageSent": "संदेश भेज दिया गया।",
  "pay.invalid": "यह भुगतान लिंक मान्य नहीं है",
  "pay.invalidBody": "मिला हुआ लिंक जांचें, या व्यापारी से दोबारा भेजने को कहें।",
  "pay.poweredBy": "DHAN द्वारा संचालित",
  "pay.error": "कुछ गड़बड़ हो गई। कृपया फिर कोशिश करें।",
};
