// Copy for DHAN AI, the Cash Calendar, and the dashboard "money waiting" / daily brief cards.

export const enAi = {
  "nav.ai": "DHAN AI",
  "nav.cashCalendar": "Cash Calendar",

  // DHAN AI chat
  "ai.title": "DHAN AI",
  "ai.sub": "Ask anything about your business. Every number comes from your own books.",
  "ai.greeting": "Namaste {name}. What would you like to know?",
  "ai.placeholder": "Ask DHAN AI anything…",
  "ai.send": "Send",
  "ai.mic": "Ask by voice",
  "ai.stop": "Stop listening",
  "ai.listening": "Listening…",
  "ai.thinking": "Looking through your books…",
  "ai.newChat": "New chat",
  "ai.how": "How I got this",
  "ai.looked": "I looked at",
  "ai.listen": "Listen",
  "ai.stopSpeaking": "Stop",
  "ai.copy": "Copy",
  "ai.copied": "Copied",
  "ai.modeGroq": "Powered by Groq",
  "ai.modeRules": "Built-in mode",
  "ai.privacyGroq": "Your question and the figures needed to answer it are processed by Groq. Raw transaction lists are never shared.",
  "ai.privacyRules": "Running on DHAN's built-in engine, so nothing leaves your account. Add a Groq key in .env for free-form answers.",
  "ai.errorTitle": "DHAN AI couldn't answer that",
  "ai.error": "Something went wrong. Please try again.",
  "ai.rateLimit": "That's a lot of questions at once. Give it a minute.",
  "ai.fallback": "The AI service was unreachable, so this answer came from the built-in engine.",
  "ai.try": "Try asking",
  "ai.s1": "How much did I spend on marketing last month?",
  "ai.s2": "Who owes me money?",
  "ai.s3": "Will I run out of cash soon?",
  "ai.s4": "What was my profit this month?",
  "ai.s5": "Who are my biggest vendors?",
  "ai.s6": "Which customers pay late?",
  "ai.askWhy": "Ask DHAN AI why",
  "ai.tool.get_summary": "Income and spending summary",
  "ai.tool.get_spending_by_category": "Spending by category",
  "ai.tool.get_top_vendors": "Biggest vendors",
  "ai.tool.search_transactions": "Transaction search",
  "ai.tool.get_receivables": "Udhaar (money owed)",
  "ai.tool.get_forecast": "30-day forecast",
  "ai.tool.get_cash_calendar": "Cash calendar",
  "ai.tool.get_credit_readiness": "Credit readiness",
  "ai.tool.get_customer_reliability": "Customer reliability",
  "ai.tool.get_insights": "Detected insights",
  "ai.late": "{n}d late",
  "ai.onTime": "On time",
  "set.int.ai": "DHAN AI (Groq)",
  "set.int.aiRules": "Built-in mode",

  // cash calendar
  "cc.title": "Cash Calendar",
  "cc.sub": "See your cash day by day and spot a tight week before it arrives.",
  "cc.insufficient": "Add about two weeks of transactions and your cash calendar will appear here.",
  "cc.safeTitle": "You're safe for the next {n} days",
  "cc.safeBody": "Cash stays above your safety buffer. Lowest point: {amount} on {date}.",
  "cc.warnTitle": "Cash gets tight around {date}",
  "cc.warnBody": "In {n} days it dips below your safety buffer of {buffer}, down to {amount}.",
  "cc.critTitle": "You could run out of cash on {date}",
  "cc.critBody": "{n} days from now your balance goes negative, unless something changes.",
  "cc.shortBy": "Short by {amount}",
  "cc.chart": "Your cash, day by day",
  "cc.now": "Today",
  "cc.buffer": "Safety buffer",
  "cc.bufferHint": "{n} days of normal spending",
  "cc.lowest": "Lowest point",
  "cc.legendBalance": "Projected cash",
  "cc.legendBill": "Bill due",
  "cc.legendInvoice": "Invoice expected",
  "cc.stress": "Stress test",
  "cc.stressSub": "What if sales dip or costs jump? Watch the line.",
  "cc.sales": "Sales",
  "cc.costs": "Costs",
  "cc.reset": "Reset",
  "cc.pSlow": "Slow month",
  "cc.pCosts": "Costs up 20%",
  "cc.pBad": "Bad quarter",
  "cc.bills": "Bills coming up",
  "cc.collect": "Money to collect",
  "cc.noBills": "No bills due in this window.",
  "cc.noInvoices": "No open invoices.",
  "cc.overdueTag": "Overdue",
  "cc.promisedTag": "Promised {date}",
  "cc.expectedTag": "Due {date}",
  "cc.rescue": "Rescue plan",
  "cc.rescueBody": "Collect {amount} from these customers to get back above your safety buffer.",
  "cc.rescuePartial": "These cover {total} of the {need} you need. Consider delaying a bill or cutting costs too.",
  "cc.remindAll": "Remind all {n}",
  "cc.reminding": "Sending…",
  "cc.reminded": "Reminders sent to {n} customers",
  "cc.remindFail": "Couldn't send any reminders. Add contact details first.",
  "cc.openReceivables": "Open Receivables",
  "cc.how": "How this is calculated",
  "cc.howBody": "Each day adds your usual income and spending for that weekday (90-day averages, one-off flagged expenses left out) and subtracts bills on their due dates. Money customers owe you is deliberately not counted as incoming, so the line stays cautious; those invoices appear in the rescue plan instead. The safety buffer is 15 days of normal spending.",
  "cc.bannerWarn": "Cash gets tight around {date}",
  "cc.bannerCrit": "Cash could run out on {date}",
  "cc.bannerCta": "See Cash Calendar",

  // dashboard cards
  "mw.title": "Money waiting for you",
  "mw.none": "Nothing is waiting. Everything is settled.",
  "mw.overdue": "{amount} overdue",
  "mw.noneOverdue": "Nothing overdue",
  "mw.claims": "{n} say they've paid",
  "mw.nextBill": "Next bill: {party}",
  "mw.in": "in {n} days",
  "mw.today": "today",
  "mw.late": "overdue",
  "mw.cta": "Open Receivables",
  "br.title": "Today's brief",
  "br.listen": "Listen",
  "br.stop": "Stop",
  "br.ask": "Ask DHAN AI",
  "br.groq": "Written by Groq",
  "br.rules": "Auto-generated",
  "br.error": "Couldn't load your brief right now.",
};

export const hiAi = {
  "nav.ai": "DHAN AI",
  "nav.cashCalendar": "कैश कैलेंडर",

  "ai.title": "DHAN AI",
  "ai.sub": "अपने व्यापार के बारे में कुछ भी पूछिए। हर आंकड़ा आपके अपने खातों से आता है।",
  "ai.greeting": "नमस्ते {name}। आप क्या जानना चाहेंगे?",
  "ai.placeholder": "DHAN AI से कुछ भी पूछें…",
  "ai.send": "भेजें",
  "ai.mic": "बोलकर पूछें",
  "ai.stop": "सुनना बंद करें",
  "ai.listening": "सुन रहा हूं…",
  "ai.thinking": "आपके खाते देख रहा हूं…",
  "ai.newChat": "नई बातचीत",
  "ai.how": "यह कैसे निकाला",
  "ai.looked": "मैंने देखा",
  "ai.listen": "सुनें",
  "ai.stopSpeaking": "रोकें",
  "ai.copy": "कॉपी",
  "ai.copied": "कॉपी हो गया",
  "ai.modeGroq": "Groq द्वारा संचालित",
  "ai.modeRules": "बिल्ट-इन मोड",
  "ai.privacyGroq": "आपका सवाल और उसका जवाब देने के लिए ज़रूरी आंकड़े Groq द्वारा प्रोसेस होते हैं। पूरी लेन-देन सूची कभी साझा नहीं होती।",
  "ai.privacyRules": "DHAN के बिल्ट-इन इंजन पर चल रहा है, इसलिए कुछ भी आपके खाते से बाहर नहीं जाता। खुले जवाबों के लिए .env में Groq की कुंजी जोड़ें।",
  "ai.errorTitle": "DHAN AI इसका जवाब नहीं दे सका",
  "ai.error": "कुछ गड़बड़ हो गई। कृपया फिर कोशिश करें।",
  "ai.rateLimit": "एक साथ बहुत सारे सवाल हो गए। एक मिनट रुकें।",
  "ai.fallback": "AI सेवा से संपर्क नहीं हो सका, इसलिए यह जवाब बिल्ट-इन इंजन से आया है।",
  "ai.try": "पूछकर देखें",
  "ai.s1": "पिछले महीने प्रचार पर कितना खर्च हुआ?",
  "ai.s2": "मुझसे किसको कितना पैसा लेना है?",
  "ai.s3": "क्या जल्दी कैश खत्म हो जाएगा?",
  "ai.s4": "इस महीने कितना मुनाफ़ा हुआ?",
  "ai.s5": "मेरे सबसे बड़े विक्रेता कौन हैं?",
  "ai.s6": "कौन से ग्राहक देर से चुकाते हैं?",
  "ai.askWhy": "DHAN AI से पूछें क्यों",
  "ai.tool.get_summary": "आमदनी और खर्च का सार",
  "ai.tool.get_spending_by_category": "श्रेणी के अनुसार खर्च",
  "ai.tool.get_top_vendors": "सबसे बड़े विक्रेता",
  "ai.tool.search_transactions": "लेन-देन खोज",
  "ai.tool.get_receivables": "उधार (बकाया)",
  "ai.tool.get_forecast": "30 दिन का पूर्वानुमान",
  "ai.tool.get_cash_calendar": "कैश कैलेंडर",
  "ai.tool.get_credit_readiness": "क्रेडिट तैयारी",
  "ai.tool.get_customer_reliability": "ग्राहकों का भरोसा",
  "ai.tool.get_insights": "पहचानी गई जानकारी",
  "ai.late": "{n} दिन देर",
  "ai.onTime": "समय पर",
  "set.int.ai": "DHAN AI (Groq)",
  "set.int.aiRules": "बिल्ट-इन मोड",

  "cc.title": "कैश कैलेंडर",
  "cc.sub": "अपना कैश रोज़ देखें और तंगी वाला हफ़्ता आने से पहले पहचानें।",
  "cc.insufficient": "करीब दो हफ़्ते के लेन-देन जोड़ें, फिर आपका कैश कैलेंडर यहां दिखेगा।",
  "cc.safeTitle": "अगले {n} दिन आप सुरक्षित हैं",
  "cc.safeBody": "कैश सुरक्षा बफ़र से ऊपर रहेगा। सबसे निचला स्तर: {date} को {amount}।",
  "cc.warnTitle": "{date} के आसपास कैश तंग होगा",
  "cc.warnBody": "{n} दिन में यह आपके सुरक्षा बफ़र {buffer} से नीचे जाकर {amount} तक गिरेगा।",
  "cc.critTitle": "{date} को कैश खत्म हो सकता है",
  "cc.critBody": "{n} दिन बाद आपका बैलेंस नकारात्मक हो जाएगा, अगर कुछ बदला नहीं।",
  "cc.shortBy": "{amount} की कमी",
  "cc.chart": "आपका कैश, दिन-ब-दिन",
  "cc.now": "आज",
  "cc.buffer": "सुरक्षा बफ़र",
  "cc.bufferHint": "सामान्य खर्च के {n} दिन",
  "cc.lowest": "सबसे निचला स्तर",
  "cc.legendBalance": "अनुमानित कैश",
  "cc.legendBill": "बिल देय",
  "cc.legendInvoice": "इनवॉइस की उम्मीद",
  "cc.stress": "तनाव परीक्षण",
  "cc.stressSub": "अगर बिक्री घटी या खर्चे बढ़े तो? रेखा को देखें।",
  "cc.sales": "बिक्री",
  "cc.costs": "खर्चे",
  "cc.reset": "रीसेट",
  "cc.pSlow": "सुस्त महीना",
  "cc.pCosts": "खर्चे 20% बढ़े",
  "cc.pBad": "बुरी तिमाही",
  "cc.bills": "आने वाले बिल",
  "cc.collect": "वसूलने वाला पैसा",
  "cc.noBills": "इस अवधि में कोई बिल देय नहीं।",
  "cc.noInvoices": "कोई खुला इनवॉइस नहीं।",
  "cc.overdueTag": "देर से",
  "cc.promisedTag": "वादा {date}",
  "cc.expectedTag": "देय {date}",
  "cc.rescue": "बचाव योजना",
  "cc.rescueBody": "सुरक्षा बफ़र के ऊपर लौटने के लिए इन ग्राहकों से {amount} वसूलें।",
  "cc.rescuePartial": "ये {need} में से सिर्फ़ {total} पूरे करते हैं। कोई बिल टालने या खर्च घटाने पर भी सोचें।",
  "cc.remindAll": "सभी {n} को याद दिलाएं",
  "cc.reminding": "भेजा जा रहा है…",
  "cc.reminded": "{n} ग्राहकों को याद दिलाई गई",
  "cc.remindFail": "कोई याद नहीं भेज सके। पहले संपर्क विवरण जोड़ें।",
  "cc.openReceivables": "बकाया खोलें",
  "cc.how": "यह कैसे निकाला जाता है",
  "cc.howBody": "हर दिन उस वार की आपकी सामान्य आमदनी और खर्च जुड़ते हैं (90 दिन का औसत, चिह्नित एक-बारगी खर्च छोड़कर) और देय तारीख पर बिल घटते हैं। ग्राहकों से मिलने वाला पैसा जान-बूझकर आमद में नहीं गिना जाता, ताकि रेखा सतर्क रहे; वे इनवॉइस बचाव योजना में दिखते हैं। सुरक्षा बफ़र सामान्य खर्च के 15 दिन का है।",
  "cc.bannerWarn": "{date} के आसपास कैश तंग होगा",
  "cc.bannerCrit": "{date} को कैश खत्म हो सकता है",
  "cc.bannerCta": "कैश कैलेंडर देखें",

  "mw.title": "आपके लिए रुका पैसा",
  "mw.none": "कुछ बाकी नहीं। सब निपट गया।",
  "mw.overdue": "{amount} देर से",
  "mw.noneOverdue": "कुछ भी देर से नहीं",
  "mw.claims": "{n} कहते हैं चुका दिया",
  "mw.nextBill": "अगला बिल: {party}",
  "mw.in": "{n} दिन में",
  "mw.today": "आज",
  "mw.late": "देर से",
  "mw.cta": "बकाया खोलें",
  "br.title": "आज का हिसाब",
  "br.listen": "सुनें",
  "br.stop": "रोकें",
  "br.ask": "DHAN AI से पूछें",
  "br.groq": "Groq द्वारा लिखा",
  "br.rules": "अपने-आप बना",
  "br.error": "अभी आपका हिसाब नहीं ला सके।",
};
