// Marathi covers navigation, sign-in, the dashboard, DHAN AI, voice, the WhatsApp bot and the main actions.
// Any key not listed here falls back to Hindi (also Devanagari), then English. See i18n.jsx.
export const mr = {
  "nav.dashboard": "डॅशबोर्ड",
  "nav.home": "होम",
  "nav.transactions": "व्यवहार",
  "nav.insights": "इनसाइट्स आणि अलर्ट",
  "nav.insightsShort": "इनसाइट्स",
  "nav.ledger": "खातेवही",
  "nav.forecast": "अंदाज",
  "nav.credit": "क्रेडिट तयारी",
  "nav.settings": "सेटिंग्ज",
  "nav.more": "आणखी",
  "nav.logout": "लॉग आउट",
  "nav.add": "व्यवहार जोडा",
  "nav.skip": "मजकुराकडे जा",
  "nav.business": "व्यवसाय",
  "nav.close": "बंद करा",
  "nav.receivables": "उधारी / येणे",
  "nav.cashCalendar": "कॅश कॅलेंडर",
  "nav.loans": "निधी (कर्ज)",
  "nav.bot": "WhatsApp बॉट",
  "nav.gst": "GST मदतनीस",
  "nav.reports": "साप्ताहिक अहवाल",
  "nav.g.money": "पैसा",
  "nav.g.intel": "बुद्धिमत्ता",
  "nav.g.grow": "वाढ",
  "nav.g.tools": "साधने",

  "common.retry": "पुन्हा प्रयत्न करा",
  "common.viewAll": "सर्व पहा",
  "common.viewDetails": "तपशील पहा",
  "common.income": "उत्पन्न",
  "common.expense": "खर्च",
  "common.expenses": "खर्च",
  "common.net": "निव्वळ",
  "common.cash": "हातातील रोख",
  "common.language": "भाषा",
  "common.loading": "लोड होत आहे…",
  "common.error": "DHAN शी संपर्क होत नाही.",
  "common.errorBody": "इंटरनेट तपासा आणि पुन्हा प्रयत्न करा.",
  "common.optional": "ऐच्छिक",

  "auth.phone": "फोन नंबर",
  "auth.password": "पासवर्ड",
  "auth.login": "लॉग इन करा",

  "dash.greetMorning": "शुभ सकाळ",
  "dash.greetAfternoon": "शुभ दुपार",
  "dash.greetEvening": "शुभ संध्याकाळ",
  "dash.add": "व्यवहार जोडा",
  "dash.today": "आज",
  "dash.month": "महिना",
  "dash.cashHeroLabel": "हातातील रोख",
  "dash.outlook": "३० दिवसांचा अंदाज",
  "dash.pulseHealthy": "सर्व काही ठीक आहे. ३० दिवसांनंतर अपेक्षित शिल्लक: {amount}.",
  "dash.pulseWatch": "लक्ष ठेवा. कमकुवत महिन्यात शिल्लक {amount} पर्यंत घसरू शकते.",
  "dash.pulseRisk": "सावधान. या वेगाने ३० दिवसांत शिल्लक {amount} पर्यंत कमी होऊ शकते.",
  "dash.attention": "तुमचे लक्ष हवे",
  "dash.allClear": "सध्या काहीही असामान्य नाही.",
  "dash.trend": "रोख प्रवाह",
  "dash.mix": "पैसा कुठे जातो",
  "dash.vendors": "सर्वात मोठे पुरवठादार",
  "dash.alerts": "इनसाइट्स आणि अलर्ट",
  "dash.forecast": "३० दिवसांचा अंदाज",
  "dash.expectedClose": "अपेक्षित अंतिम शिल्लक",
  "dash.worst": "सर्वात वाईट स्थिती",
  "dash.best": "सर्वात चांगली स्थिती",
  "dash.expected": "अपेक्षित",
  "dash.credit": "क्रेडिट तयारी",

  "mw.title": "तुमचे येणे पैसे",
  "mw.cta": "उधारी उघडा",
  "rv.title": "DHAN ने वसूल केले",
  "rv.body": "DHAN ने आठवण करून दिल्यानंतर {n} बिलांवर {amount} मिळाले",

  "ai.title": "DHAN AI",
  "ai.placeholder": "DHAN AI ला काहीही विचारा…",
  "ai.mic": "बोलून विचारा",
  "ai.stop": "ऐकणे थांबवा",
  "ai.listening": "ऐकत आहे…",
  "voice.speakIn": "या भाषेत बोला",
  "voice.tap": "दाबा आणि बोला",
  "voice.listening": "ऐकत आहे…",
  "voice.stop": "थांबवा",
  "voice.processing": "DHAN समजून घेत आहे…",
  "voice.failed": "आवाज समजला नाही. पुन्हा प्रयत्न करा किंवा खाली टाइप करा.",
  "voice.example.mr": "आज जीएसटी पोर्टलला पाचशे रुपये भरले",

  "act.title": "सुचवलेली योजना",
  "act.approve": "मंजूर करा",
  "act.skip": "वगळा",
  "act.approveAll": "सर्व मंजूर करा",

  "bt.title": "WhatsApp बॉट",
  "bt.photo": "बिलाचा फोटो पाठवा",
  "bt.photoSent": "फोटो",
  "ln.title": "निधी (कर्ज)",
};
